### ISSUE TITLE
Enhancement: Owncloud feed requests contain batch-size -1 on all feed update requests

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#112]
#### Brief description of the issue.

Owncloud requests get batch-size -1 (which means all) added to the requests. Over time, this might be a big number of items, that are send over at every feed update.

E.G.: /apps/news/api/v1-2/items?id=1&batchSize=-1&type=0

#### How to reproduce the bug?

1.  Do a owncloud feed update.

#### What is the expected result?

Maybe limit to the last 50 or 100 feed items?

#### What actually happened?

All items are send over.

#### Other information (logs, see Wiki)

None needed.

**Comment by martinrotter** [comment]
I will fix like this:

1. If this feed is updated for the first time within this app run, then all messages (batch size -1).
2. Every next feed update, only new or modified messages are downloaded.

**Comment by martinrotter** [comment]
Does the mentioned way of fixing this is enough for you? Or maybe do you want this configurable - to specify the number of messages to download?

**Comment by groentebroer** [comment]
Hi,
Both have advantages and disadvantages.

I think having the number of items configurable, makes it also possible to set it to "-1". So for backward compatibility as well as creating the ability to be as fault-tolarant as possible is still in there.
(E.G. when having issues, you can re-read the complete feed by setting it to -1 and setting it back aftwards to for example 100.)

So that would be my preferred method.

**Comment by martinrotter** [comment]
> I think having the number of items configurable, makes it also possible to set it to "-1"
This is actually a valid point.

Okay, will try.

**Comment by martinrotter** [comment]
b8f7d14
 I added the support, so far WITHOUT SAVING THE LIMIT - so it gets reset to default value "-1" after each RSS Guard start.

**SO please test the feature, and if it is OK, then I will finalize it so that the setting is stored persistently in the DB.**

**Comment by groentebroer** [comment]
I checked it and it works OK! The request contains the limit correctly.

The implementation is currently a complete "reset" of the feeds based on a changed limit. Ideally someone might want to get all items with "-1" and then change it to "100" to only update new items. This is not feasable with the current implementation. If this has a lot of complications, keep it this way, it will suffice. If not that much of work (edge cases), that would be a real plus.

**Comment by martinrotter** [comment]
I am not sure what you are trying to say with "The implementation is currently a complete "reset" of the feeds based on a changed limit."

Could you elaborate?

**Comment by groentebroer** [comment]
After editing the settings, all feeds are removed below the owncloud/nextcloud account. The feed list is retreived from nextcloud again and after that the items in the feed are retrieved with the correct limit. 

Effectively this only gets the limited number of items, where previously it could have had more items. But due to the complete renewal of the feed list from owncloud these old items which belonged to the "old" feeds are removed.

**Comment by martinrotter** [comment]
Oh this, yes, this is so far default behavior and it was there even before this ticket.

When user clicks OK in settings dialog of OwnCloud account, then the data of the account are completely reset:
 - all local DB data is erased (local categories, feeds, messages, everything),
 - sync-in on account is triggered (the account feed tree is reset) and new categories/feeds are downloaded.

So even if user does not change anything in account settings, it is reset as long as he clicks OK. Maybe I could enhance the behavior to check if the user actually changed some settings. This new approach will of course ignore our limit, so that account WILL NOT be reset when user just goes in changes the limit number.

But this all is probably a separate issue, please, create new ticket for this, so that we do not mix two things in single ticket.

So I will add persistent limit number saving to DB and we will be done in this ticket.

**Comment by martinrotter** [comment]
Settings are now persistently stored/loaded to/from DB.
