### ISSUE TITLE
[BUG]: Gmail cant be added - The app isnt verified

### ISSUE THREAD

**Issue by inson1** [martinrotter/rssguard#1165]
### Brief description of the issue

Sorry for czech.
![image](https://github.com/martinrotter/rssguard/assets/75314629/557539a2-134b-461e-befd-e7808ea498ae)

### How to reproduce the bug?

Add Gmail account - network proxy
google shit - Go to rss guard web (dangerous) - something gone wrong

### What was the expected result?

Add gmail account with my inbox

### What actually happened?

error

### Debug log

"something gone wrong"

### Operating system and version

Brave
RSS guard: 4.5.1

**Comment by martinrotter** [comment]
![image](https://github.com/martinrotter/rssguard/assets/1255302/a5931ece-e823-496a-bb6f-e776af3a0bf2)
see red rectangle, click that

You see this dialog because Gmail API is very strict about which "official/safe" apps can use it and apps must be "verified" which is very tedious process.

I highly recommend you to generate your own access tokens in google developer console and not use preconfigured tokens.

https://console.cloud.google.com/cloud-resource-manager?pli=1

**Comment by inson1** [comment]
@martinrotter I already did that
google shit - Go to rss guard web (dangerous) - something gone wrong

**Comment by martinrotter** [comment]
how does your gmail acc settings dialog in rssguard looks like

also, if you open bug reports, you must provide debug logs

https://rssguard.readthedocs.io/en/stable/contrib/bugs.html
