### ISSUE TITLE
Queue for podcasts

### ISSUE THREAD

**Issue by bengan** [martinrotter/rssguard#1248]
### Brief description of the feature request

Hi,

I would like to listen to podcasts in the background while browsing other articles or podcasts. But the podcast I'm listening to stops when I click on another feed/podcast article. I saw that I could open the audio/mpeg in another tab which solves the problem and is fine but it took a while to find. Podcasts in particular are a bit of a serial queue feature. Maybe have an "open in new tab" as default for podcasts, or "open podcasts in tab for podcast queue". If you then click on another podcast, it can be queued for playback.

**Comment by martinrotter** [comment]
So basically, you want to have something like playlist in media player.

> But the podcast I'm listening to stops when I click on another feed/podcast article.

This is usually not the case, internal media player is launched when you right-mouse-click any link and press "play in media player".

**Comment by sn0utss** [comment]
I think these are two separate requests...? I don't care about queuing personally however:

> This is usually not the case, internal media player is launched when you right-mouse-click any link and press "play in media player".

This launches the media player in the same tab, replacing the feed list - which is suboptimal to just sending straight to mpv via "Open with external tool". Afaict in order to have the media player open in a secondary tab which can be left on in the background while you return to the feed list, you actually have to open two empty new browser tabs first...?

**Comment by martinrotter** [comment]
> This launches the media player in the same tab, replacing the feed list 

@sn0utss This is definitely not standard expected behavior. Media player always opens in new tab. Please post a screenshot or screencast video to see to behavior.

**Comment by sn0utss** [comment]
Confirm tab issue resolved in latest dev.

**Comment by martinrotter** [comment]
So we can basically close this?
