### ISSUE TITLE
[BUG]: Flatpak Version number  is incorrect

### ISSUE THREAD

**Issue by cement-head** [martinrotter/rssguard#1251]
### Brief description of the issue

The update has an older version number than the current install.  Attempt same via CLI and get better diagnostic messages.

### How to reproduce the bug?

1. Notification of update via package manager (Pop_OS! Shop)
2. Run package manager
3. Get error (message/screenshot below)

### What was the expected result?

Updated to next iteration

### What actually happened?

Update crashed, versioning incorrect.

### Debug log

![Screenshot from 2023-12-11 10-07-48](https://github.com/martinrotter/rssguard/assets/1056700/0c2a55bd-10d9-4a95-87f3-c7e610faf304)

### Operating system and version

* OS: Pop_OS! 22.04 LTS
* RSS Guard version: 4.6.2 (Flatpak installation)

**Comment by mmkthecoolest** [comment]
As a sidenote: on flathub.org, the [non-lite program identifies as the lite program](https://flathub.org/apps/io.github.martinrotter.rssguard). This was addressed in #1243 which was the same release as 4.6.2. Since 4.6.1 is the latest on Flathub for the non-lite version, this issue exists again.

**Comment by mmkthecoolest** [comment]
Wait why is this closed now? It still seems to be an issue on my end.
![image](https://github.com/martinrotter/rssguard/assets/27556124/6d6b026d-7e4e-43c6-8494-d456c34d5ce6)

**Comment by zestygrass** [comment]
I have the same issue as @mmkthecoolest 
The naming being wrong on flathub is definitely confusing as well.

Can this issue be re-opened @cement-head or should I open a new issue?

**Comment by martinrotter** [comment]
@guihkx

**Comment by guihkx** [comment]
*sigh*...

I think I know exactly what happened:

1. I tried to publish version 4.6.1 as soon as it was released, but the build was withheld by Flathub because of [this bug](https://github.com/martinrotter/rssguard/issues/1242), meaning this version would require manual approval by a Flathub admin to be published on the Flathub store
2. Then, the next day version 4.6.2 was released and it fixed the bug above. So I built it and released asap
3. A Flathub admin manually approves the publishing of version 4.6.1, which ends up replacing the 4.6.2 build

I will report this to the Flathub admins, but solving this issue should be fairly easy, I think: I just have to manually trigger a rebuild of RSS Guard, and the issue should be gone in a few hours.

In any case, @martinrotter please leave this open until things get fixed. 

Thank you everyone.

**Comment by martinrotter** [comment]
Well I will release next version on a few days...

**Comment by guihkx** [comment]
That's great, but it shouldn't be needed to fix this issue in particular.

I've already manually triggered a [rebuild](https://buildbot.flathub.org/#/builders/6/builds/87368), which should hopefully fix things in the next hours (because Flathub delays the publishing of builds by at least 3 hours).

I just hope that this rebuild doesn't also require manual approval by a Flathub admin...

**Comment by mmkthecoolest** [comment]
[Seems 4.6.2 is live now](https://flathub.org/apps/io.github.martinrotter.rssguard)

**Comment by zestygrass** [comment]
It is fixed, Thank you @guihkx
