### ISSUE TITLE
[FR]: Support for RSS-HUB

### ISSUE THREAD

**Issue by LSP0123** [martinrotter/rssguard#1256]
### Brief description of the feature request

i'm useing RSS-HUB now ,but rssguard doesn't support `feed:// ` , i must add feed one by one .

Is there any plan to support `feed:// `

**Comment by martinrotter** [comment]
Please describe exactly what you want to to and how you try to do it and what does not work.

AFAIK RSS.hub generates standard "http://......." RSS/ATOM feeds, like these:

https://rsshub.app/19lou/jiaxing
https://rsshub.app/axis-studios/work/full-service-cg-production
https://rsshub.app/dev.to/top/month

**Comment by LSP0123** [comment]
![image](https://github.com/martinrotter/rssguard/assets/31061624/0107bd0a-48fc-4849-bf39-ae98fd6710a0)
when i use  “Subscribe to a local reader” function in RSS hub Rader ,it always open outlook. couldn't auto open Rssguard and subscribe

**Comment by martinrotter** [comment]
What is the left option? Don't post Chinese stuff which no one can read omg 😳

**Comment by LSP0123** [comment]
![image](https://github.com/martinrotter/rssguard/assets/31061624/ece351f9-50e4-49d9-98bc-61c4d08d905f)

this one? (复制)  it is "copy", 

😂Changing the language of windows is too bad for me。I will upload a screenshot with English later。
The display of the RSSHUB Rader extension should be similar between Chinese and English

**Comment by martinrotter** [comment]
What is copied when you hit copy

**Comment by LSP0123** [comment]
the first one:  https://rsshub.rssforever.com/github/comments/martinrotter/rssguard/1256

This URL can be entered into the rssguard field ,but "Subscribe to  local reader" buttom won't turn on rssguard .

"Subscribe to  local reader" buttom will open `feed://https://rsshub.rssforever.com/github/comments/martinrotter/rssguard/1256` in browser. Edge will show  `This site is trying to open Outlook`

![image](https://github.com/martinrotter/rssguard/assets/31061624/1f3556a7-f845-49fd-bbf1-555bbdfe23e1)

https://github.com/DIYgod/RSSHub-Radar/issues/731

DIYgod said that rssguard doesn't support `feed://` to subscribe  and i should to  feedback to rssguard

**Comment by martinrotter** [comment]
"feed:" protocol is fully supported by rssguard, but maybe its functionality is broken, i will check on monday

**Comment by martinrotter** [comment]
https://rssguard.readthedocs.io/en/stable/features/cli.html

**Comment by martinrotter** [comment]
So, I checked the situation.

RSS Guard itself does support "feed:" and "feed://" schemes.

![image](https://github.com/martinrotter/rssguard/assets/1255302/a5c64c3f-7d6e-4164-81f0-e83a9e32af71)

Your problem is that you do not have RSS Guard registered for "feed:" URL handler in Windows OS, which is not RSS Guard's fault.

When I click "Local reader" in RSS.hub extension, then my web browser (firefox) asks me to set application to handle the request. I select "rssguard.exe" and then the request is correctly handled by RSS Guard and this window appears.

![image](https://github.com/martinrotter/rssguard/assets/1255302/2fe10672-1f2d-494d-98df-84846272dbe9)

Remember, for this to work, you already have to have your RSS Guard installed and at least one RSS/ATOM account added - "Add account" dialog is automatically shown when RSS Guard starts for the first time.

**Comment by LSP0123** [comment]
I had added the account ,but When I click "Local reader" in RSS.hub extension, Edge Browser always ask me to open outlook

![image](https://github.com/martinrotter/rssguard/assets/31061624/c0ee8b18-2ff3-4a30-9650-621144282b5d)

**Comment by martinrotter** [comment]
Well, then you have to somehow change it from outlook to rssguard.

In Firefox, this happens.

![image](https://github.com/martinrotter/rssguard/assets/1255302/a7110a76-0338-4cf7-ac71-460923ee6136)

![image](https://github.com/martinrotter/rssguard/assets/1255302/ca597f5c-3de3-4a19-b148-57090ee05a7f)

![image](https://github.com/martinrotter/rssguard/assets/1255302/aa1bcfbd-bccd-4ed6-a038-e921e8c095c0)
