### ISSUE TITLE
[BUG]: YT RSS feeds are being received with wrong date

### ISSUE THREAD

**Issue by netglitch7** [martinrotter/rssguard#1258]
### Brief description of the issue

I use RSSGuard mainly to get notification about YouTube channels I follow. Some videos that were published days ago are arriving as a new item with today's date. For example, in this image, this video was upload 11 days ago (12/07/2023), but it appears on RSSGuard as it was released today (12/18/2023).

I tried other RSS apps using the same .OPML file with all my YouTube subscriptions (QuiteRSS, Liferea, etc) and this behavior does not happen.

YouTube RSS Feeds are being used with this format (example):
`https://www.youtube.com/feeds/videos.xml?channel_id=UCCE3tX_wa3C90T40sUgctjQ`

![1](https://github.com/martinrotter/rssguard/assets/154277271/1ebed997-3b2f-4cc8-b1da-96dc6d59a301)

### How to reproduce the bug?

1. Import an OPML file with YouTube subscriptions
2. Use RSSGuard for some time

### What was the expected result?

Old videos should arrive with the correct date

### What actually happened?

Old videos are being show with the incorrect date

### Debug log

No Logs

### Operating system and version

* OS: Arch Linux (kernel 6.6.7-arch1-1)
* RSS Guard version:
```
Version: 4.6.3 (built on Linux/x86_64)
Revision: 
Build date: 12/15/23 1:24 PM
Qt: 5.15.10 (compiled against 5.15.10)
```

**Comment by martinrotter** [comment]
Yes, this is caused by the fact that RSS Guard is extremely "precise" when it comes to handling incoming RSS articles.

This was already reported many times.

Youtube sometimes erratically changes "updateTime" of some RSS articles when it should not and RSS Guard recognizes this and believes that article was **updated** but it really was not.

I will try to check if rssguard is not to blame (it likely is not). You can easily solve this behavior with article-filtering feature which allows you to ignore "updated" versions of already saved articles.

**Comment by netglitch7** [comment]
> Yes, this is caused by the fact that RSS Guard is extremely "precise" when it comes to handling incoming RSS articles.
> 
> This was already reported many times.
> 
> Youtube sometimes erratically changes "updateTime" of some RSS articles when it should not and RSS Guard recognizes this and believes that article was **updated** but it really was not.
> 
> I will try to check if rssguard is not to blame (it likely is not). You can easily solve this behavior with article-filtering feature which allows you to ignore "updated" versions of already saved articles.

First, sorry about opening an issue that was already opened many times, I did a quick search but did not find anything related to that, and it was totally my fault.
And second, thank you very much about this tip, I didn't know about this article-filter feature! Do you have a step-by-step on how to do that anywhere? If not, I can try to figure out myself :)

**Comment by RetroAbstract** [comment]
Applying [this article filter](https://github.com/martinrotter/rssguard/issues/416#issuecomment-849365155) and [this one](https://github.com/martinrotter/rssguard/issues/1261#issuecomment-1883017890) **separately** to YouTube feeds solves this.

**Comment by disabledautomatic** [comment]
> Applying [this article filter](https://github.com/martinrotter/rssguard/issues/416#issuecomment-849365155) and [this one](https://github.com/martinrotter/rssguard/issues/1261#issuecomment-1883017890) **separately** to YouTube feeds solves this.

Sorry to reopen this old issue, but the first filter script doesnt work anymore in 5.0 and im not sure how to fix it. It spits out this when i try to fetch with it.

> TypeError: Cannot read property 'published' of undefined
>line: 8
>stack: filterMessage@:8
>%entry@:1

With line 8 being this:

> publishedDate = jsonObj.entry.published.__text;

Considering that the two lines before this one run without error, im not even sure where to start.

I changed MessageObject to Msg already because i saw that this changed, but i dont understand this script well enough to debug it.

**Comment by martinrotter** [comment]
This hack is now not needed.

RSS Guard 5 added direct setting to allow you to choose if you want "Updated" or "Published" dates in each feed.

Go to feed settings -> experimental and there it is.

**Comment by martinrotter** [comment]
<img width="576" height="98" alt="Image" src="https://github.com/user-attachments/assets/89c18d1b-b61d-45e4-9f4c-2ad860947bd6" />
