### ISSUE TITLE
Is there as list of recommended icon themes?

### ISSUE THREAD

**Issue by AndyM48** [martinrotter/rssguard#1390]
### Brief description of the feature request

None of the icon themes I have tried are complete, which messes up the user interface.

I am on Arch linux.

Thanks

**Comment by martinrotter** [comment]
Hi.

Yes, sadly using icon themes is a PITA because like you noticed, many icon themes are missing some "semi-standard" icons etc.

RSS Guard for Windows is optimized for icon themes listed in this directory

https://github.com/martinrotter/rssguard/tree/master/resources/graphics

so these are safe/complete to use on Linux too.

Please write me which icon themes you tried and I will add icon names to RSS Guard to make it work better with those themes. Thanks.

**Comment by AndyM48** [comment]
Most icon themes fall back to` hicolor`, which does not work.
`elementary` theme only partially works.
`elementary-xfce` almost works.
`oxygen` theme works well.

Hope that helps.
