### ISSUE TITLE
[FR]: Support for Boolean Search Operators

### ISSUE THREAD

**Issue by touwys** [martinrotter/rssguard#1397]
### Brief description of the feature request

Please consider adding support for the following set of Boolean search operators to deploy in RSS Guard Article Search:

Reference: <a href="https://www.scribbr.com/working-with-sources/boolean-operators/">[Boolean Operators | Quick Guide, Examples & Tips](https://www.scribbr.com/working-with-sources/boolean-operators/)</a>

Thank you.

•

![image](https://github.com/martinrotter/rssguard/assets/65730626/2b2485c3-7a9a-4d2f-a2f7-1db5bd20b998)

**Comment by martinrotter** [comment]
What do you mean? Article filtering feature already allows for binary logical expressions, same standrd for article list filtering which supports regex which allows the same logic (although with different syntax and with limitations).

Where exactly you miss this feature?

**Comment by touwys** [comment]
> Where exactly you miss this feature?

In the `Search Articles` search bar.

> Article filtering feature already allows for binary logical expressions

Could you please provide an example of such a "binary logical expression"? I am not familiar with the term. For instance, how does one search for the word "pagan", without getting the word "propaganda" added to the search results?

> ... article list filtering which supports regex ...

 I imagine that the application of regular expressions leans more toward the domain of power users, whereas regular folks can learn how to use Boolean operators with little trouble. Also, people using browser search engines, e.g. Google, are usually already familiar with the latter.
_

**Comment by martinrotter** [comment]
Yes, some features of RSS Guard have more of a steep learning curve and that's fine. Other features are easier to use. RSS Guard is very specific application for specific target audience, developed completely free of charge in my free time, so yes, many features might be missing for some users.

As of regular expressions matchin "pagan" word. There is "word boundary" support on regex.

This search phrase `\bpagan\b` will match exactly all "pagan" words, but not "propaganda". Here is example for searching "Windows 10" se separate word.

![image](https://github.com/martinrotter/rssguard/assets/1255302/99194553-c41e-4658-b6a4-d172c8f8165b)

Sadly, with my (lately) severely limited free time (3 kids + regular full time job + I am sitting on town council board + other hobbies + work around my garden, house) it is nearly impossible for me to implement all features I would like. Simply do not have the time. Even bug fixing is very problematic last months due to time...

To use binary logical expression in ARTICLE FILTERS feature, you have to study related documentation which states that those scripts are written in JavaScript/ECMAscript which provides its own docs on how to write different things.
