### ISSUE TITLE
[BUG]: issue with image parsing with css2rss

### ISSUE THREAD

**Issue by seventyiris83** [martinrotter/rssguard#1477]
### related to [#8](https://github.com/Owyn/CSS2RSS/issues/8)

when i use css2rss to get rumble videos as articles in rss guard using this as post-process script:

`python css2rss.py "[role='listitem']" "h3" "img"`

in 4.3.3 lite it correctly appends video thumbnails to the articles:

![000000001](https://github.com/user-attachments/assets/2f69625d-96b3-4ec0-a40f-114cae8ccc6c)

in 4.7.2 lite and 4.7.3 lite it doesn't:

![000001](https://github.com/user-attachments/assets/a9a602df-b3ba-4490-982b-242b380e4f14)

### How to reproduce the bug?

have 4.3.3 lite and 4.7.2 lite or 4.7.3 lite on your system
have css2rss installed
add a new feed with this url: https://rumble.com/c/LofiGirl
add `python css2rss.py "[role='listitem']" "h3" "img"` as post-process script
fetch the feed articles
see the difference between 4.3.3 lite and 4.7.2 lite/4.7.3 lite

### What was the expected result?

4.7.2 lite to append the video thumbnails to articles (jpg urls)

### What actually happened?

4.7.2 lite appends an unwanted section of the `img` item resulting in no video thumbnail appended

### Debug log

N/A

### Operating system and version

* OS: Windows 10
* RSS Guard version: 4.7.2 lite/4.7.3 lite

**Comment by martinrotter** [comment]
will look into this

**Comment by martinrotter** [comment]
Check it.

Sadly, the internal RegExp which extracts information about images from HTML article is confused because your HTML excerpts contain this:

<img alt="Lofi Girl's red scarf 🧣" class="thumbnail__image" draggable="false" height="270" loading="lazy" onerror="this.onerror=null;this.**src=**"data:image/svg+xml,%3Csvg width='480' height='270' xmlns='http://www.w3.org/2000/svg'/%3E"" src="https://1a-1791.com/s/s8/1/L/7/z/k/L7zko.oq1b.2-small-Lofi-Girls-red-scarf-.jpg" width="480"/>

Specifically, HTML contains "src=" part which is in fact no the real source of the picture - this piece of code is embedded JavaScript.

I tried to tweak the logic a bit and it all seems to work. Sadly the regular expression approach will not work for 100% of websites. If some problem arises in the future, I will have to re-think the approach and maybe use full XML/HTML parsing to extract source URLs of images.

**Comment by seventyiris83** [comment]
thanks for looking into this 😄

i tested the build containing the change and it does now work! the images are appended to articles.

but it's the same result as before when "use legacy article formatting" is enabled:

![000001](https://github.com/user-attachments/assets/a9a602df-b3ba-4490-982b-242b380e4f14)

could your fix also be applied to the legacy article formatting?
