### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by Johandrex** [martinrotter/rssguard#149]
There's currently no way to know when RSS feeds are being updated. In the Tray & Notification center it says that the tray icon is unavailable, which disables the notification options as well. (https://i.gyazo.com/4a5e9de550b349a05b5e82ea526d4dba.png).

I've read the Wiki which states that there's a "desktop integration via tray icon", which must mean that there's something wrong on my end (or something wrong with the latest update?). I'm a new user and love the reader so far. I'm using Windows 10 and a local RSS account.

**Comment by martinrotter** [comment]
RSS Guard asks OS if it supports tray icons with message balloons, if OS says that these are not supported, then the functionality is disabled in RSS Guard.

Specifically, [this](http://doc.qt.io/qt-5/qsystemtrayicon.html#isSystemTrayAvailable) API is used. It is weird, because Win10 should of course work.

Anyway, I tried to fix it in 3619250a. Wait for it to get compiled and then download latest development build AND LET ME know here if it works now. - https://github.com/martinrotter/rssguard/wiki/Windows-development-builds

**Comment by Johandrex** [comment]
Tried https://transfer.sh/7QKN3/rssguard-3.5.1-8e78f60-nowebengine-win64.exe, sadly didn't work.

**Comment by martinrotter** [comment]
Too soon, you need file with 3619250 in it, wait for it to compile, should be in 10 minutes.

**Comment by martinrotter** [comment]
https://transfer.sh/11Tm4y/rssguard-3.5.1-3619250-nowebengine-win64.exe

**Comment by Johandrex** [comment]
The tray works perfect now thanks, I do however not get any popup messages when a new RSS update comes (the tray does however show the amount of unread messages).

**Comment by martinrotter** [comment]
Yes, because you have balloons disabled by some regedit hacks. On vanilla Windows 10, balloon messages should work.

https://stackoverflow.com/questions/3002030/qsystemtrayicon-does-not-show-message

**Comment by martinrotter** [comment]
This is not RSS Guard issue probably. Feel free to add comments, tho.

**Comment by Johandrex** [comment]
Thanks, the regedit solved it.

**Comment by martinrotter** [comment]
OK, now I will revert the patch so that the RSS Guard detection is ok.
