### ISSUE TITLE
Folder enhancements

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#200]
There are two small issues I found:
1. When changing icon theme, the folder icons are not changed accordingly.

Example - I switched to KFaenza icon theme, folder created used dark grey default folder icon. After changing to Breeze and restarting the program, icons does not change to the white default folder icon. The UI itself respects the theme change.

---

2. A double-click on a folder shows/hides the sub-items, but the folder icon itself does not change. To explain it further; usually there are two folder icons, one for open folder and one for a closed folder. But the question here is if rssguard uses both or just one.
Since there is possible to use a custom icon, an icon overlay would be probably a better option.

When I have time, I can check the source code to see how to fix that but I opened this issue to check with someone with Qt experience if this is doable or not.

**Comment by martinrotter** [comment]
As for 2 - RSS Guard uses just one and the same icon for closed and opened folders.

As for 1 - folder icons of your folders are stored directly in RSS Guard database file (SQLite) and they are not loaded from icon themes at this point. They are treated exactly the same as feed icons, which are also read from RSS Guard DB file, so that they remain untouched when user decides to switch desktop/app icon theme.

So if you select "use default icon" option, it takes the icon from active icon theme and stores its contents into RSS Guard DB and then uses this exact data forever, until you change the icon.

========
That said, I just commited a fix for this which:
 - removes option to use category/feed without icon
 - if user selects "use default icon" for feed/category, then real default icon from current icon theme will be used all the time and icon will NOT be copied to RSS Guard DB
 - user can still select arbitrary picture file as icon if he really wants

So now, default icons of feeds/categories should really follow your icon theme. Note that your currently existing feeds/categories are not affected and you need to re-import them.

**Comment by martinrotter** [comment]
478b03a025cb563025b279886751171c43d43c09
