### ISSUE TITLE
3.6.3 build fails

### ISSUE THREAD

**Issue by lgbaldoni** [martinrotter/rssguard#238]
#### How to reproduce the bug?

1. Download rssguard tarball version 3.6.3
2. Try to build it on openSUSE Tumbleweed
3. See log

#### What is the expected result?

A successful build.

#### What actually happened?

The build fails

#### Other information (logs, see Wiki)

[Relevant log snippet](https://github.com/martinrotter/rssguard/files/4722252/rssguard-3.6.3.txt).
Using Qt 5.14.1 and gcc9. A similar problem also occurs with Qt 5.12.7 and gcc7.

**Comment by martinrotter** [comment]
I see, should be fixed in master. Weird thing is that on Ubuntu, Windows and Mac OS X, it compiled just fine. Magic.

**Comment by martinrotter** [comment]
7b64bc31

**Comment by lgbaldoni** [comment]
Works for me now, any chance it's due to the default flags used on OBS?
(`-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables`)

**Comment by martinrotter** [comment]
No, AFAIK it is due to quirks found in specific GCC/clang versions. I found out that particularly GCC is very fragile and each its version loads dependent "#include" C++ headers in a different way. Each compiler does it differently thus on some platforms no error is raised because compiler somehow finds correct header files (probably included in C++ file which was compiled before this errorneous file), and on other platforms it just does not. Maybe it is also related to order in which C++ files are compiled...
