### ISSUE TITLE
FreshRSS

### ISSUE THREAD

**Issue by Tealk** [martinrotter/rssguard#252]
Hello,

is it possible to integrate FreshRSS into the reader?
https://github.com/FreshRSS/FreshRSS

**Comment by martinrotter** [comment]
Hello @Tealk. Yes it is possible for RSS Guard to support FreshRSS reader, but there would have to be BIG BIG BIG interest from community and if it will be, then I will implement the plugin.

Or someone else can contribute plugin implementation, I will be very happy to merge it into RSS Guard. Plugin API is there, and is stable and working well.

**Comment by Tealk** [comment]
FressRSS offers the following API's but this also requires a plugin?
Google Reader API
Fever API

**Comment by martinrotter** [comment]
@Tealk No, you don't have to do anything on the side of FreshRSS, someone has to implement C++ plugin into RSS Guard codebase, so that RSS Guard knows how to call the API.

At this point, there is a total of 6 plugins implemented in RSS Guard and all of them are directly compiled into RSS Guard application. RSS Guard can also load plugins as library files (DLL files on Windows).

https://github.com/martinrotter/rssguard/tree/master/src/librssguard/services

For example Inoreader has implemented plugin in RSS Guard and is known to work just fine, although implemented functionality is rather basic.

Plugins must be implemented in C++ programming language and must implement `ServiceEntryPoint` and `ServiceRoot` interfaces.

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/services/abstract/serviceentrypoint.h

https://github.com/martinrotter/rssguard/blob/master/src/librssguard/services/abstract/serviceroot.h

I believe that Inoreader's plugin source code would be a good start.

https://github.com/martinrotter/rssguard/tree/master/src/librssguard/services/inoreader

**Comment by martinrotter** [comment]
Closing for now, if you will be interested in writing the plugin, let me know.
