### ISSUE TITLE
isDuplicateWithAttribute(16) in "Message filters" not working

### ISSUE THREAD

**Issue by Eleferen** [martinrotter/rssguard#263]
#### Brief description of the issue.

`isDuplicateWithAttribute(16)` in "Message filters" not working or i am not using it correctly.

#### How to reproduce the bug?

1. Menu Messages-->Message filters
2. Settings:
![image](https://user-images.githubusercontent.com/15795413/89632206-84aa1380-d8aa-11ea-9382-b802262780e9.png)

Code filter:
`function filterMessage() {
  if (msg.isDuplicateWithAttribute(2) && msg.isDuplicateWithAttribute(16)) {
    return 2;
  } else {
    return 1;
  }
}`

#### What was the expected result?
Identical messages from different feed do not get

#### What actually happened?

Duplicated message from different feed
![image](https://user-images.githubusercontent.com/15795413/89632160-6fcd8000-d8aa-11ea-92c1-6b7b63796772.png)

#### Other information
Version: 3.7.1 (built on Windows/x86_64)
Revision: 8ca1b7f
Build date: 05.08.2020 13:21
Qt: 5.14.2 (compiled against 5.14.2)

Localisation: Russian (does not affect bug reproduction)
Windows 10 64bit

**Comment by martinrotter** [comment]
I commited d40409f6
Please wait for it to compile and test again, also provide full application debug outpit, please. :)

**Comment by martinrotter** [comment]
OH, and by the way, you are probably using it incorrectly.

That parameter is an enum which also supports bitwise OR operations. Using it just with parameter `16` will not work, because you need to also "enable" some attribute. If you want to check if message is duplicate by **URL** and take *all* feeds into account then you need to combine input values `2` and `16` into single parameter and perform only single call to `isDuplicateWithAttribute`. Like this:

```
function filterMessage() {
  if (msg.isDuplicateWithAttribute(2 | 16)) {
    return 2;
  } else {
    return 1;
  } 
}
```

**Comment by Eleferen** [comment]
Replaced as you suggested. The result can be understood only after some time (several days). Thank you.

**Comment by martinrotter** [comment]
@Eleferen So, any news?

**Comment by Eleferen** [comment]
The function seems to work correctly: `...if (msg.isDuplicateWithAttribute(2 | 16)) {...`
Thank you.
