### ISSUE TITLE
Percent signs (%) not showing in message title and not being seen by filters

### ISSUE THREAD

**Issue by mpr0st** [martinrotter/rssguard#267]
#### Brief description of the issue.

Message titles lost percent signs in titles, in message list and filters.

#### How to reproduce the bug?

1. Subscribe to a feed which contains messages with percent signs in the title.
2. Update.

#### What was the expected result?

The messages show the full title in the message list, for example: Save 98% off this Ultimate Data and Project Management Certification Bundle. If there's any filter expecting, for example, "98%" in the title, the message gets correctly filtered.

#### What actually happened?

The messages show an erroneous title: Save 98off this Ultimate Data and Project Management Certification Bundle

![image](https://user-images.githubusercontent.com/49242687/89814272-2a77af80-db43-11ea-8460-25915b31c74d.png)

The messages don't get filtered.

#### Other information (logs, see Wiki)

Thank you.

**Comment by martinrotter** [comment]
Can you post URL of feed which contains such messages?

**Comment by mpr0st** [comment]
Here you'll have some of them: http://www.neowin.net/news/rss/

Thank you.

**Comment by martinrotter** [comment]
Yes, RSS Guard sanitizes some attributes of each downloaded message (title, author, url, contents) before messages are passed to filters and stored to DB.

There is some trickery, because some feeds provide quite messed titles (embedded HTML, newlines, many consecutive whitespaces etc.).

Anyway, I disabled "percent-decoding" feature and now it should work. Test on dev. build and let me know.

**Comment by mpr0st** [comment]
OK, thank you. I will have to wait for the next message, will report back.

**Comment by mpr0st** [comment]
It works! Thank you!
