### ISSUE TITLE
open in internal browser tab uses only 1/2 screen

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#284]
i have previews off and when I click to open in internal browser and switch to the tabs i have opened that way the internal broswer seems to use only the top half of the screen

**Comment by martinrotter** [comment]
Yes, I realized this too. I made some big changes to internal message viewer to make it work nicely with labels". I will think about this and try to make it much better.

**Comment by martinrotter** [comment]
@pcause This gives me a headache.

To explain: It is very (very, very, very) difficult to make message "preview" widget to resize/expand automatically to fit all HTML contents. While it is doable for single message, it is nearly impossible to have this correctly done for newspaper view. "non-webengine" version of RSS Guard has newspaper now fixed in my working copy but I need to decide what to do with web-based newspaper view, options are:
1. Hard-code the value so that each message in newspaper view has the same height as the RSS Guard window. Therefore, each message will tak 100% of available space.
2. Do not hardcode the value and merge all messages into SINGLE "webview" which will then load much faster and will correctly resize itself to fit available space. This solution has one critical downside, message tweaking buttons (mark read/unread/important, tweak labels) will NOT be available in this newspaper view mode.

What you think?

**Comment by martinrotter** [comment]
@pcause I for now implemented option 1, which looks reasonable and keeps all the nice features: 
![image](https://user-images.githubusercontent.com/1255302/98079244-c3347780-1e73-11eb-9ec2-82885ea0c568.png)

Test latest revision: 93fc5415
