### ISSUE TITLE
What to do when downloading "unread" message only

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#286]
If user has enabled "download only unread" option, then only unread messages are downloaded. Some users also requested that if this is the case, then also all **other** messages should be marked as read in the process, because if they were not downloaded then they must be **read**, workflow:

1. Download new messages.
2. If "download unread only" is enabled, do also this:
    a. Mark all other messages in account as read.
    b. Sync those **read** changes back to server?

**Comment by pcause** [comment]
i use tt-rss and download unread only. i set fetch unread only because i have 150+ feeds and keep 30-45 days history so a full sync would be really slow.  After I sync there are more articles unread locally than on than server because rssguard leaves read status for local articles unchanged unless it gets a change from the server and when you fetch unread only you don't see a status change from your last fetch of articles that flip from unread to read.  . i know you can't get a changed since type update from the tt-rss api. i thought you'd get the id's of unread articles you have locally and then any that aren't in the unread article update list from the server would be marked as read locally. so the logic would be:

    get unread ids from local database. keep in memory or temporary table
    use tt-rss api to get unread articles. remember ids.
    for ids not in list of fetched id'sfrom server,  but in list of local unread id from first step, mark read locally and sync that back to     server

Issues with this:
- if an article is changed on server (starred/labeled) but is unread, you can miss the change since it won't be unread and your local copy won't have this.  This is no worse than if I marked all read manually before a sync and was only fetching unread articles.

**Comment by martinrotter** [comment]
this issue is now redundant because now there is PoC of better sync algorithm for greader plugin and i will gradually over time implement this for other plugins too.
