### ISSUE TITLE
end user thoughts on nowebengine

### ISSUE THREAD

**Issue by CouldBeThis** [martinrotter/rssguard#303]
Hello, 

New user here just went to download this application for the first time. (I haven't even used it yet; just straight to Issues lol) I have some feedback on just that. 

**nowebengine vs full: explain the difference**

The information about the relevance of the "nowebengine" variants *is technically* [available](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#documentation) if you look for it. But it should be available on the Releases page, which is the moment when it is useful to know about.

I'd suggest a brief 1 sentence explanation such as "NoWebEngine is a smaller, bare bones version that runs faster but with fewer bells and whistles. Click [here](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#web-based-and-lite-app-variants) to read more." (Or something like that, which is perhaps more accurate.)

**nowebengine naming**

From an end user perspective, it would be much more intuitive to call it "Lite" or something because "nowebengine" really doesn't mean anything at all. If you _really_ want to keep it that way minimally change to NoWebEngine because it at least looks like english. 

**app name**

The actual app (I downloaded for Mac) should have a different file name so both can be installed if, for instance, someone wanted to try both out. Like `RSS Guard Full` and `RSS Guard nowebengine` etc. (Obviously they can be renamed but why not make it simple because I got myself confused.) 

**does nowebengine affect privacy?**

I am not sure if I am correct, but I guess that maybe nowebengine might have some effect on tracking, cookies, and such? if so maybe it bears mention in the explanation because some people are interested in that. 

thanks for making this program, now that I'm done this, I look forward to trying it out. :)

**Comment by martinrotter** [comment]
nowebengine vs full: explain the difference
---
Well, the difference between normal version and **no-web-engine** version is exactly that, nowebengine version has NO WEB ENGINE. Nothing more, nothing less. Some minor technical differencies are there and they are describe in documentation as you brightly noticed. Also, as majority of users intuitively expects, version without any web technologies is actually more **safe** and respects your **privacy** more, as again, is written in documentation.

Using "lite" word to describe the package is in this case highly misleading and just wrong.

nowebengine naming
---
As written above, "lite" is VERY VERY incorrect wording here. It is not lite version, it is just normal fully featured RSS Guard w/o web engine capabilities.

app name
---
Can you perhaps create separate distinct bug ticket for this? It could certainly make sense to implement it. Moreover, RSS Guard really desperately needs someone technically skilled to **fix** the MacOS RSS Guard version because it is known to not work - #147 - for many people, the package is inherently broken and fixing it is very difficult for me as I do not own mac machine.

does nowebengine affect privacy?
---
As stated in docs, webengine version contain Chromium-based code, which although being open-source, could be perceived as problematic for many people. 

Thank you for your contribution. :)
