### ISSUE TITLE
Symantec AV alert on installer

### ISSUE THREAD

**Issue by jonnyt1978** [martinrotter/rssguard#306]
#### Brief description of the issue.

Symantec (corporate) AV reports the following alert on the RSS Guard installer:

Risk name: WS.Reputation.1 
File path: ..\rssguard-3.8.2-12104c7-win64.exe 

#### How to reproduce the bug?

1. Have Symantec (corporate) AV installed
2. Download RSS Guard 64-bit installer
3. Try to run installer

#### What was the expected result?

No AV alert

#### What actually happened?

AV alert and installer put in quarantine by AV

**Comment by martinrotter** [comment]
Just tested with VirusTotal, no detections trigerred.

https://www.virustotal.com/gui/file/9a0febc2c441f4314bff1bf3a745ae432daca0ed4168df9121b3ebcfff3c7a02/detection

Sorry. If you want to avoid false positives then build RSS Guard perhaps by yourself, use 7z archive instead of installer or perhaps use better AV solution. :)
