### ISSUE TITLE
3.8.4 - feed sorting should be case insensitive

### ISSUE THREAD

**Issue by pcause** [martinrotter/rssguard#319]
in the 3.8.4 the feed sorting is case sensitive.  at a point in past it was case insensitive.  think insensitive is best since user may lack control of naming.

**Comment by martinrotter** [comment]
Are you 100% positively sure that sorting is case sensitive? Because in the code I see that case insensitive sorting is setup and I also tested RN, and it works as expected - notice for example category Fun & life - sorted according to tile ascendingly: 
![image](https://user-images.githubusercontent.com/1255302/102085757-59ff3700-3e17-11eb-9676-8d04a8370b62.png)

**Comment by pcause** [comment]
the last 2 feeds are lower case but if case insensitive should obviously be positioned differently

![image](https://user-images.githubusercontent.com/1071479/102216087-8e83f900-3ed2-11eb-825a-a2a2f026446f.png)

**Comment by martinrotter** [comment]
So you are talking about list of MESSAGES not list of feeds.

**Comment by martinrotter** [comment]
OK, fixed, wait until b09d3ecf gets compiled and test pls. The bug was affecting all columns in message list in fact.
