### ISSUE TITLE
[BUG]: repeated notifications for the same feed

### ISSUE THREAD

**Issue by norbusan** [martinrotter/rssguard#329]
#### Brief description of the issue.

When checking for new feeds, a new feed gives one new notification everytime it is checked for, instead of one notification for the first time it is detected.

#### How to reproduce the bug?

1. add some feeds
2. select "Auto-update all feed ..."
3. wait for a new feed being notified
4. don't open rssguard from the systray, leave it there
5. on the next auto-update there will be another notification

#### What was the expected result?

Only one notification per new feed item.

#### What actually happened?

One notification per feed item **per update check**

#### Other information

* OS: Debian
* Desktop Environment: KDE/Plasma 5.20.4
* RSS Guard version: 3.8.3

Example for the multiplication of notifications:

![image](https://user-images.githubusercontent.com/1735589/102690857-ad281e00-424b-11eb-8d33-de96088c09ea.png)

**Comment by martinrotter** [comment]
I see, does this happen with only some specific feeds? If you see multiple "Planet Debian: 1" messages, do you subsequently see only 1 unread message? Or is it possible that indeed there was coincidentally 1 new message each time RSS Guard check for it periodically?

Can you share URL of feed which has this behavior?

**Comment by norbusan** [comment]
Hi Martin,

thanks for looking into this. And, no, there is only one new entry, and the notification is for the same one.

The feed I am using is from PLanet Debian: https://planet.debian.org/rss20.xml

**Comment by martinrotter** [comment]
Could you please provide full application log when reproduced the problem?

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file

**Comment by martinrotter** [comment]
@norbusan Looking at the LOG you provided. So you use "Nextcloud" plugin in RSS GUard?

**Comment by norbusan** [comment]
Hi

Will do all of that, but probably after Christmas ;-)

**Comment by norbusan** [comment]
I have built rssguard now from the git head, and it seems to behave much better wrt nextcloud news. In the last days I haven't seen duplication of notifications.

I close the issue for now, it seems to be fixed with the upcoming version.

Thanks a lot.

**Comment by norbusan** [comment]
Hi Martin
I am sorry to say that with 3.9 the problem has reappeared. NextCloud as News provider, and repeating notifications every 15min (the interval I let it check).

I am collecting a debug log now, and if you think that helps I will send it when the duplication happens again.

**Comment by martinrotter** [comment]
@norbusan Yes, please, provide a concise set of steps to exactly reproduce the issue (what exact feeds trigger the bug or all feeds? what nextcloud version, what news version) + debug log.

I will test in days with clean devbuild and nextcloud news.

**Comment by martinrotter** [comment]
So, I investigated the issue and I believe it is now properly fixed. The problem was that RSS Guard by mistake treated date/time information returned by Nextcloud as being in `localtime` and not `UTC`. This caused the fact that in subsequent updates RSS Guard thought that time of article has changed when in fact it wasn't.

**Comment by norbusan** [comment]
Martin, that is great! I was collecting the data and you fixed it already.
I have included the patch into the Debian package 3.9 (only file location has changed) and did run it since yesterday without any duplications.

Much appreciated.

**Comment by norbusan** [comment]
@martinrotter One question: the patch changed the semantics of 'static QDateTime parseDateTime(qint64 milis_from_epoch)' and that has fixed it for NextCloud, but the same function is being used in a lot of other providers, doesn't this create a problem with other providers?

**Comment by martinrotter** [comment]
@norbusan 
I chcked all usages of `parseDateTime(qint64)` and it should be all good. There was some problematic behavior of [`fromMSecsSinceEpoch`](https://doc.qt.io/qt-5/qdatetime.html#fromMSecsSinceEpoch-1) method which seems to sometimes behave weirdly because when it takes the amount of miliseconds since epoch it treats those miliseconds as absolute time in local timezone, which is in fact not what I wanted (I did not read documentation) because I as a Linux guy naturally expected that it would NOT recalculate the time into local timezone but would keep in in UTC...

I store the timestamps into RSS Guard database as total absolute msecs since epoch and keep it in UTC so the problem was that I was subsequently comparing UTC value from DB and localtime value from new downloaded message.

**Comment by martinrotter** [comment]
@norbusan 
> I have included the patch into the Debian package 3.9

Well, I plan to release some bug-fix `3.9.x` releases soon, I will backport this to 3.9.1 then.

**Comment by norbusan** [comment]
Thanks @martinrotter for the confirmation, much appreciated. I will ask for a freeze exception to get rssguard 3.9 + the bugfix into Debian/bullseye.
