### ISSUE TITLE
[FR]: ARM64 support

### ISSUE THREAD

**Issue by morgannunan** [martinrotter/rssguard#330]
#### Brief description of the feature request.

I am looking for an RSS reader that works with Nextcloud, that I can use on my Mobian Pinephone. This program is very close, and the fact that there's a horizontal view and I can hide the sidebar, means it would work well on my phone. However, the phone is ARM64 and RSS Guard doesn't support it yet. Great program though!

**Comment by martinrotter** [comment]
Hello @morgannunan.
There is no ARM64-specific stuff/code in RSS Guard. There are ARM64 builds available, notably Debian has added RSS Guard to their experimental repositories and they have ARM64 build, but I have never tested it.

https://packages.debian.org/sid/rssguard

Here is link to ARM64 packages - http://ftp.de.debian.org/debian/pool/main/r/rssguard/rssguard_3.8.3+dfsg-1_arm64.deb

Not sure if that is what you want. I could maybe somehow test in with Raspbian in VirtualBox. I do not have any raspberry pi or something else with Linux distro on it.

Moreover, RSS Guard is compilable directly for Android and AFAIK there are some users who compile it by hand and probably use it as well. I myself tried it last time like two years ago and it is fair to note that it was running, but UX was horrible because RSS Guard is primarily developed for desktop stations and all GUI element follow that goal.

**Comment by martinrotter** [comment]
Btw let me know if the above answer is good enough so that I can eventually close this ticket.

**Comment by morgannunan** [comment]
This was a great answer. Thanks for responding so quickly. It's working on my phone now!
