### ISSUE TITLE
[BUG]: Clicking "login" on inoreader account does nothing

### ISSUE THREAD

**Issue by trwnh** [martinrotter/rssguard#352]
#### Brief description of the issue.

The login button does not seem to work.

#### How to reproduce the bug?

1.  Add Inoreader account
2. Fill out username (and optionally, OAuth 2 app details)
3. Click "Login"

#### What was the expected result?

OAuth login window opens somewhere

#### What actually happened?

Nothing happens

#### Other information

* OS: Arch Linux
* Desktop Environment: XFCE
* RSS Guard version: 3.8.4

Tried via official repos and also via Flatpak. Same issue regardless.

**Comment by martinrotter** [comment]
@trwnh It seems that default Qt method for opening external web browser is somehow faulty, especially on Linux. The only thing I can do right now is to maybe display messagebox with target URL if function fails, but I suspect that the method falsefully returns "true" result even if it failed.

**Comment by martinrotter** [comment]
@trwnh Check this: https://github.com/martinrotter/rssguard/blob/master/src/librssguard/network-web/oauth2service.cpp#L328

The code is already there. You should see popup window with the URL to copy and open by hand.

The code respects settings from Tools -> Settings -> Web browser -> External web browser, so to workaround the upstream bug, please, check the checkbox, browser your web browser binary and save settings. Should work.

![Uploading image.png…]()

**Comment by trwnh** [comment]
Nope, still does nothing when I click the button. :(

**Comment by martinrotter** [comment]
@trwnh Damn, I tested now with Vivaldi on Linux and on Windows and it works. Give me some time, will investigate.

**Comment by martinrotter** [comment]
@trwnh OK, test with latest dev. build again please. THank you.

**Comment by martinrotter** [comment]
https://imgur.com/a/ktn9Z1c

**Comment by martinrotter** [comment]
Also, provide test with latest dev. build, including log file. See documentation on how to produce log file.

**Comment by trwnh** [comment]
```
time="    16.265" type="critical" -> oauth: OAuth redirect handler FAILED TO START TO LISTEN on address '127.0.0.1' and port '80'.
time="    16.265" type="critical" -> oauth: Cannot log-in because OAuth redirection handler is not listening.
```

**Comment by martinrotter** [comment]
Yes, and you should probably see red text in

![image](https://user-images.githubusercontent.com/1255302/106439050-8890aa00-6477-11eb-971f-e067893decc7.png)

if you tested in in latest development version. Since you are Arch user, I would expect you are a bit technically skilled. The error is saying that it cannot start local HTTP server on port 80, probably because there already is some service blocking that port or maybe because ports smaller than 1024 are only accessible for ROOT users. Therefore you need to click "Get my own.." button

![image](https://user-images.githubusercontent.com/1255302/106439331-da393480-6477-11eb-907b-8323e5aab7cc.png)

and setup your "oauth application" by hand with custom redirection URL with higher port, something like "http://localhost:1444".

This effectively solves the issue.

**Comment by trwnh** [comment]
> ports smaller than 1024 are only accessible for ROOT users.

Huh. TIL!

For anyone coming across this issue in the future, here is what you can do:

1) Set a redirect in your app to a port higher than 1024, as suggested above, or
2) Run `sudo setcap CAP_NET_BIND_SERVICE=+eip /bin/rssguard` to grant access to bind to port 80. Run `sudo setcap -r /bin/rssguard` to remove the capability

I'd also recommend changing the default port away from 80, perhaps?

**Comment by trwnh** [comment]
I'd submit a PR but I'm not sure where to make the change...

**Comment by martinrotter** [comment]
> > ports smaller than 1024 are only accessible for ROOT users.
> 
> Huh. TIL!
> 
> For anyone coming across this issue in the future, here is what you can do:
> 
> 1. Set a redirect in your app to a port higher than 1024, as suggested above, or
> 2. Run `sudo setcap CAP_NET_BIND_SERVICE=+eip /bin/rssguard` to grant access to bind to port 80. Run `sudo setcap -r /bin/rssguard` to remove the capability
> 
> I'd also recommend changing the default port away from 80, perhaps?

There is already a change in RSS Guard development version (to be release as 3.9.0) which displays big red text if local oauth listener cannot be started due to this port problem. Inoreader account comes with predefined credentials which will suit more users but I will also register one more oauth with custom port to make it all work for linux users too. On Windows, there is no < 1024 limitation.

**Comment by trwnh** [comment]
As best as I can tell, wouldn't this line be the cause?

https://github.com/martinrotter/rssguard/blob/5efae020c3e421e6d0a6355988a67face4f62b1d/src/librssguard/services/inoreader/gui/inoreaderaccountdetails.cpp#L53

Searching for OAUTH_REDIRECT_URI, I can see that there is also a OAUTH_REDIRECT_URI_PORT that goes unused in the Inoreader account details UI. Wouldn't it be better to setText(OAUTH_REDIRECT_URI + ':' + OAUTH_REDIRECT_URI_PORT) and change the default app registration to point to port 13377?

**Comment by martinrotter** [comment]
The line is partially a cause and I re-implemented it to include the new default port "14488" for all oauth applications in RSS Guard and I also created a new pre-defined ID/key for Inoreader so it should now work out-of-box for all new users.

797cdb55

**Comment by martinrotter** [comment]
> and change the default app registration to point to port 13377?

Btw I cannot change redirection port in existing inoreader oauth "application" because it could break stuff for existing user. But nevermind it is all now fixed with totally new registration and bug-fix in rss guard.
