### ISSUE TITLE
[FR]: 1 minute update interval

### ISSUE THREAD

**Issue by guixxx** [martinrotter/rssguard#355]
#### Brief description of the feature request.

Hi, is there a reason for RSS Guard to not allow update intervals lower than 3 minutes? I have a "critical" feed that I need to update once a minute, so I wonder if this feature could be added. Thank you in advance.

**Comment by martinrotter** [comment]
@guixxx No, there is no specific reason, I believe I decided for minimum of 3 minutes due to "cosmetic" reasons. I will adjust it and allow for 1 minute.

**Comment by martinrotter** [comment]
It is done. Note that you need newest dev. build to get the features and also, because of the nature of the fix, the feature will probably NOT work with your existing data. You need to start RSS Guard with clean data folder and re-import your feeds because the update_interval minimum constraint was stored directly in the DB and I will not make auto-migrating SQL script for such a small change. :)

So the easiest way - wait for new release, and start with clean data folder. :)

**Comment by guixxx** [comment]
No worries! Thanks for the heads up.
