### ISSUE TITLE
[BUG]: Sometimes thick feed entry lines

### ISSUE THREAD

**Issue by CsatiZoltan** [martinrotter/rssguard#357]
#### Brief description of the issue.

Some feed entry lines become "thick", i.e. they consume multiple lines (see the video attached).

#### How to reproduce the bug?

I don't exactly know its cause so I cannot give an exact reproducibility guide. It happens when new feeds are downloaded, but not all the time.

#### What was the expected result?

I would expect that the entries do not get thicker. As you can see in the video attached, for some feed accounts it works as expected, while for others the feed entry lines get thicker. I don't think it has to do with the specific feeds because most of the time normal feed entry line widths are displayed for all of my incoming feeds. Restarting RSS Guard does not solve this issue.

#### Other information

* OS: Linux/x86_64
* Desktop Environment: Gnome 3
* RSS Guard version: 3.8.4, revision 7ab95a75
* Qt version: 5.14.2

https://user-images.githubusercontent.com/12742890/106880766-0dc8c880-66dd-11eb-8c0b-20dd1a7eff4e.mp4

**Comment by martinrotter** [comment]
@CsatiZoltan Yes, this seems to be cause by multiline text which appears in some of the cells of the list.

Technically, the GUI library computes the "height" if first row, and then applies this height to all remining rows and does not compute row height for each row for better performance. So if first row includes multiline text, all rows will be affected, even if they do not need to be that thick.

Could you share your "database.db" file with data with the issue with me?

**Comment by CsatiZoltan** [comment]
@martinrotter From the video, I conclude that the issue is with [this feed](http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1097-0207), particularly with [this item](https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.6648). As you can see, the authors' names makes it very long.
When I selected another folder (which does not contain the problematic feed), there is no such issue because the item information is short for them.
One solution I have in mind is to allow the user to select an option that keeps the line at default height by truncating information.

**Comment by martinrotter** [comment]
OK, the feed contains multiple authors on single message which are separated by NEWLINES, which is horrible behavior from the feed.

I would recommend you to create "message filter" which will get applied to all message(s) of the feed automatically. Message filters are a powerful feature that allows you to automatically modify contents of messages which are being downloaded by RSS Guard.

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Message-filters.md#message-filtering

I wrote a sample message filter for you: 

```js
function filterMessage() {
  msg.author = msg.author.replace(/(\r\n|\n|\r)/gm, "");
  return MessageObject.Accept;
}
```

which automatically removes all newlines from "author" field of every message.

![image](https://user-images.githubusercontent.com/1255302/107017630-ad4e8f80-679f-11eb-99ff-9710adbd0f06.png)
![image](https://user-images.githubusercontent.com/1255302/107017717-c6574080-679f-11eb-846d-99f9cdd1c508.png)

You simply copy the filter, go to main menu Messages -> Message filters, create new filter, check your feed, inter filter's contents from above and optionally click "Process checked feeds" and everything should be now ok.

Thing is that I am not sure if it is good way to sanitize "author" field globally for everyone as it could break existing functionality. And one more thing, it is primarily the fault of the feed, because including newlines in "author" field is just bad.

Anyway, try the above solution and let me know. Do not forget to read linked documentation VERY carefully as "message filters" are fairly advanced feature.

**Comment by CsatiZoltan** [comment]
> I wrote a sample message filter for you:

Thank you, I don't know Javascript.

> the feed contains multiple authors on single message which are separated by NEWLINES

Where do you see it? I can't see a `<br>` tag or `\n` in the [feed URL](https://onlinelibrary.wiley.com/action/showFeed?jc=10970207&type=etoc&feed=rss) I sent.

> Thing is that I am not sure if it is good way to sanitize "author" field globally for everyone as it could break existing functionality. And one more thing, it is primarily the fault of the feed, because including newlines in "author" field is just bad.

Completely agree.

> try the above solution and let me know.

I already deleted the entries from last time, so I will wait for the next time this issue happens, and I will then activate the filter to try it out.

**Comment by martinrotter** [comment]
@CsatiZoltan 
![image](https://user-images.githubusercontent.com/1255302/107025886-4f737500-67aa-11eb-82c9-f1b19bd662e5.png)

Always download XML to file, because browsers like Chrome automatically "pretty-print" xml when displaying it.

**Comment by CsatiZoltan** [comment]
@martinrotter Thanks, I always learn something new.

**Comment by CsatiZoltan** [comment]
I tried it for new entries and it works well. According to the [workflow](https://github.com/martinrotter/rssguard/blob/master/resources/docs/Message-filters.md#message-downloadingfiltering-workflow), I had to re-download entries becasue a filter is applied after downloading entries, and not on existing ones. Thanks again.
