### ISSUE TITLE
[BUG]: Install VC++ runtime libs in RSS Guard installer instead of unpacking it

### ISSUE THREAD

**Issue by fredddii** [martinrotter/rssguard#375]
Following errors prevent it from opening:

The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.

The code execution cannot proceed because MSVCP140_1.dll was not found. Reinstalling the program may fix this problem.

**Comment by martinrotter** [comment]
Due to Microsoft's licensing policy, all needed runtime libraries are distributed with RSS Guard in file "vc_redist.x64.exe". Therefore you can unpack RSS Guard from `7z` archive or install via installer, then go to its destination folder and launch "vc_redist.x64.exe".

I will maybe reconsider putting libs directly into the package.

**Comment by fredddii** [comment]
@martinrotter When RSS Guard was installing, in the log list I saw it doing something with a vc_redist.x64.exe file.

It went too quick so I am not sure what it was doing (installing, unpacking, ...), but is it not possible to just have the correct Visual C++ runtime installed during the RSS Guard installation process?

**Comment by martinrotter** [comment]
Yes, I already took a note about it and will add it to the installer, so that installer will not just unpack redist but also install it. :)

https://github.com/martinrotter/rssguard/issues/361

**Comment by fredddii** [comment]
Thank you again!

**Comment by martinrotter** [comment]
Fixed.
