### ISSUE TITLE
[BUG]: "Select next unread message" seems to scroll to a random part of the message list instead of to the selected message

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#389]
#### Brief description of the issue.

Title pretty much says it all, forces me to scroll down a bunch in the message list to actually find which unread message is selected. However, the correct information is in the bottom-right pane (the details of that message).

#### How to reproduce the bug?

1. Have unread items
2. Set a keyboard shortcut for "select next unread message"
3. Press that key while currently highlighted item is anything on the left pane (not in any feed's message list, but your account, a feed name, the "labels" row, etc.)

#### What was the expected result?

The unread item's message list should appear on the right (it does), and it should scroll down to display the now-highlighted unread item. In other words, the same behavior you get if you hit the "select next unread message key" while some item in any message list is highlighted.

#### What actually happened?

The correct message list appears, but it does not scroll down properly to the unread item that was selected, making you scroll down manually, sometimes a lot, before seeing it highlighted in the message list.

#### Other information

* OS: Win10 x64
* Desktop Environment: not sure what you mean by this
* RSS Guard version: 3.9.0

**Comment by RandomNerd1** [comment]
Let me know if I should add this as a separate feature request, but I think when it's acting correctly, "select next unread message" should scroll down so that the highlighted message (within the message list) is at the top of the viewable portion of the message list, not the bottom. There are several feeds where if there are several unread items (which often come at the same time), you would want to see as many of them (in the message list) as possible at once at a glance, and I'm finding myself scrolling down instinctively every time I do it.

**Comment by martinrotter** [comment]
I am not able to reproduce, can you make a video? Here is what (correctly) happens on my side. This feature works for me for ages, I used it every day. Here is the demonstration where I start RSS Guard and repeatedly hit my shortcut for "show next unread message".

It just works for me.

![ksGnaW4z2J](https://user-images.githubusercontent.com/1255302/111989214-c625c100-8b11-11eb-9559-dce6d4a18aef.gif)

**Comment by martinrotter** [comment]
Oh, now I get it. So the feature in fact works (it selects correct messages), but your concern is that the message is not correctly "scrolled" to? You would prefer to have scrolled target message placed in the top of viewport?

**Comment by RandomNerd1** [comment]
Yes, the 'feature request' part of it would have me prefer that, but the bug part is that you can't see the highlighted message at all, if you go to it the way I describe.

**Comment by martinrotter** [comment]
Ah, I see, I managed to reproduce the problem and fixed it. Also, I tweaked scrolling behavior a bit to move selected item rather to top of the viewport than to bottom.

f7213472

**Comment by martinrotter** [comment]
Pls, test the fix with latest just compiled development build and let me know if it works.

**Comment by RandomNerd1** [comment]
Seems to work perfectly. A couple of things, though...

I just realized that it seems your stable 3.9.0 release (https://github.com/martinrotter/rssguard/releases/download/3.9.0/rssguard-3.9.0-a939e237-win64.exe) installed itself by default to the "Program Files (x86)" folder (I'm on Windows), even though it's labeled as a 64-bit version. I only realized this when your development build did not default to that folder (in fact, did not default to the other "Program Files" folder, either, but instead wanted to be in the root of the C: drive).

So I installed the development build to "C:\Program Files\RSS Guard" and it installed just fine. Question is, is there an easy way to transfer the settings and tweaks I've made so far in the existing installation, to this new one, so that I can just uninstall the old one, and use this until 4.0.0 stable comes out? Or do I have to start all over?

**Comment by martinrotter** [comment]
@RandomNerd1 

RSS Guard 4.x.x will have some hugely different DATABASE structures and also some backwards-compatible hacks removed, simplified, made faster etc.

At this point, you can probably transfer your `config.ini` file which will very likely work just fine. As for `database.db` DATABASE file. Well, its structure is vastly different and there is probably no sane way of converting 3.x file to 4.x file, but you can of course export all your feeds to OPML file and then import it into new version.

That said, I backported some of the bug-fixes to 3.9.x line and will release one or two bug-fix releases for 3.9.x soon. I expect RSS Guard 4.0.0 to come out in several months' time.

Also, keep in mind that RSS Guard binaries you see in "development builds" are meant to be highly fragile and experimental and things will BREAK between individual development builds.

> Seems to work perfectly. A couple of things, though...

Yes, I still think about the issue and I will probably make it work in a more unified way, because there is also

![image](https://user-images.githubusercontent.com/1255302/112099957-a8556c00-8ba4-11eb-8567-666678af8a72.png)

which conflicts a bit with new behavior. I will make it work even a bit better soon.
