### ISSUE TITLE
[BUG]: YouTube RSS feeds seem not to work at all

### ISSUE THREAD

**Issue by RandomNerd1** [martinrotter/rssguard#392]
#### Brief description of the issue.

Title pretty much says it all

#### How to reproduce the bug?

1. Add a YouTube feed like

https://www.youtube.com/feeds/videos.xml?user=billwurtz for a 'user'

https://www.youtube.com/feeds/videos.xml?channel_id=UCqg5FCR7NrpvlBWMXdt-5Vg for a 'channel'

(I have no idea why some YouTube channels are 'users' and others are 'channels', I think it's something to do with YouTube partnership or something)

2. Watch it never add any content to the feed

Both of the above URLs produce data when you try to open them in Firefox, so I know they're functional. They also work in quiteRSS, still.

#### What was the expected result?

YouTube channel updates without 'subscribing' :D

#### What actually happened?

Nothing D:

#### Other information

* OS: Win10 x64
* RSS Guard version: 3.9.0

**Comment by martinrotter** [comment]
@RandomNerd1 
1. I downloaded RSS Guard https://github.com/martinrotter/rssguard/releases/download/3.9.0/rssguard-3.9.0-a939e237-win64.7z.
2. I added both above feeds.
3. Messages got downloaded just fine, no errors.

![image](https://user-images.githubusercontent.com/1255302/112100724-dc7d5c80-8ba5-11eb-99fe-e97ce409a50f.png)

![image](https://user-images.githubusercontent.com/1255302/112100734-e1421080-8ba5-11eb-9448-595dd380e055.png)

![image](https://user-images.githubusercontent.com/1255302/112100752-e737f180-8ba5-11eb-9274-4aeec9440f94.png)

So. What happens if you add one of those URLs and click "Fetch it now" button in `Add/Edit feed` dialog?

**Comment by martinrotter** [comment]
Also, provide debug log

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#generating-debug-log-file

**Comment by RandomNerd1** [comment]
I don't know what to say, but after fighting with it for almost half an hour earlier today, now it's working perfectly.

I guess I can close this one, lol...

**Comment by martinrotter** [comment]
@RandomNerd1 Wait, so what was the original problem? What you had to change?

**Comment by RandomNerd1** [comment]
I didn't change anything. When I saw your reply, I went to try again, and now it's working perfectly. No idea what was going on...

**Comment by martinrotter** [comment]
OK, perhaps some random network error. I will remove this ticket entirely. :)
