### ISSUE TITLE
Many files in the repo are executable

### ISSUE THREAD

**Issue by jn64** [martinrotter/rssguard#414]
Many files in the master branch have executable permissions set. Just wondering since there does not seem to be any pattern in it. For example, some pngs in `resources/docs/images` are 775 while some are 664, even though they were added in the same commit. 

I noticed this because it carried over to the Fedora package, installing some files with the executable bit in places where it's not expected (like `/usr/share/icons`).

**Comment by martinrotter** [comment]
Yes, I usually do not really care about file permissions on my working copies. I also have `filemode` option in Git set to `ignore` and because I use multiple operating systems for RSS Guard development I have really no other option and I like to ignore permissions completely.

It is up to packages to set proper permissions when compilling RSS Guard and I would like to keep it that way.

Also, git does NOT actually keep track of read/write permissions, it only remembers executable bits (AFAIK) and I myself also do not really care about these since because often if you set `+x` on Linux, push, and fetch on Windows your executable bits will mess up sometimes so it is quite a hell.

Sorry for any inconvenience, simply use your `umask` and reset permission of all files upon pull, cleanest way.
