### ISSUE TITLE
[BUG]: feed working on v3.8.5

### ISSUE THREAD

**Issue by pipiscrew** [martinrotter/rssguard#443]
#### Brief description of the issue.
feed working on v3.8.5, on v3.9.2 is unable to parse

`https://jlelse.blog/index.xml`

* OS: Win10
* RSS Guard version: 3.9.2

**Comment by sakkamade** [comment]
> `https://jlelse.blog/index.xml`

Works fine for me. With either 3.9.2 and dev. build. Arch Linux.

**Comment by sakkamade** [comment]
Confirmed. 

Cannot fetch it on Windows 10 [Version 10.0.19042.928], RSS Guard dev. build: `Network error: host not found`.

**Comment by martinrotter** [comment]
@pipiscrew Yes, I reproduced it. Problem is caused by improper handling of HTTP redirection in libraries used by RSS Guard. Apparently, they have there some bug which happens only on Windows.

Thing is that in 3.8.x I was doing redirectiony "manually" and in 3.9.2+ I let the library do them automatically.

I will try to revert to older behavior. Redirections are generally rather problematic stuff.

**Comment by martinrotter** [comment]
It's done. Feel free to test and report back if needed.
