### ISSUE TITLE
#843b4312 has really slowed down Bazqux synchronization

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#454]
I have no idea why, but the July 27 dev version #843b4312 (on Windows 10 Pro 20H2, fast internet connection) has really slowed down Bazqux sync to a crawl.

Thanks for all the work on this. Appreciated!

**Comment by martinrotter** [comment]
Yes, I currently do some PoC work on Greader plugin and at this point the work is not finished and in fact current unfinished implementation is semi-broken and will be slow or even not functioning! Use some older development build if possible.

I am trying to develop MUCH faster syncing algorithm for the plugin and because each implementation of Google Reader API is in some ways esoteric (especially TheOldReader), the work is not easy.

https://github.com/martinrotter/rssguard/issues/398

I expect to continue on the code tomorrow and things will get implemented in a matter of days/weeks. Hopefully, we will get MUCH MUCH faster synchronization soon. Especially subsequent fetching of feeds will/should be much faster. I will close this ticket and will post any relevant new in https://github.com/martinrotter/rssguard/issues/398. :)
