### ISSUE TITLE
[FR]: Could we have a keyboard shortcut option for 'toggle minimize-maximise app', please?

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#456]
As above. Thanks!

**Comment by sakkamade** [comment]
> toggle minimize-maximise app

You want RSS Guard to have configurable global shortcut for "Switch main window visibility"?

Like this?
![rss guard visibility](https://user-images.githubusercontent.com/62730422/128291558-b49b5d86-1c6a-4d40-9cb6-9d8aeb363d3a.png)

**Comment by umbellipher** [comment]
Thanks. Hadn't spotted that. Setting a shortcut and activating it appears, for me, to minimize the app to the notification bar (not the taskbar), but it then will not maximize again on use of the same shortcut. It's not a major issue.

**Comment by sakkamade** [comment]
> to minimize the app to the notification bar (not the taskbar)

If you disable the tray icon it will be minimised where you want it to.

> but it then will not maximize again on use of the same shortcut.

You may open a separate issue addressing it.

**Comment by martinrotter** [comment]
> but it then will not maximize again on use of the same shortcut
Once application is minimized and its window no longer has focus, then regular application-wide keyboard shortcut will not work anymore. You would need "global" keyboard shortcut working system-wide for this.

**Comment by martinrotter** [comment]
You can follow-up this.

RSS Guard is single-instance application, but it has extra feature: If you launch "rssguard" binary while RSS Guard is already running, then its main window will be displayed/restored even if minimized/hidden before. Simply try to launch RSS Guard once more when it's already running.

**Comment by sakkamade** [comment]
> Once application is minimized and its window no longer has focus, then regular application-wide keyboard shortcut will not work anymore

> And global keyboard shortcuts are very hard to support in a cross-platform manner.

This is what I also thought, but then why does it say "...and shows if it is hidden"? 
What are conditions under which it _will_ work, then?

**Comment by martinrotter** [comment]
because i think (but not sure) that I also have this action in tray icon menu

**Comment by sakkamade** [comment]
> because i think (but not sure) that I also have this action in tray icon menu

Yes, at least of the same name. So? I am not sure I follow you.

**Comment by martinrotter** [comment]
I tweaked name of standing action to "Minimize (or hide) main window" as it is what it really does and also removed it from tray icon menu as the same effect can be achieved with clicking on the tray icon and thus the menu item was redundant.

As for showing hidden main window, this is currently not possible because there is no modern x-platform Qt module which would provide global keyboard shortcuts.

There are some [older](https://bitbucket.org/libqxt/libqxt/wiki/Home) 3rd-party projects which offer global keyboard shortcuts but the only support subset of our supported OSes (X11/Linux, Win, MACOS) they lack support of (OS/2, Wayland/Linux, etc.).

There would have to be much greater interest in this from many users for me personally to implementing global shortcuts. So I am closing the issue until that happens. :)

At this point as stated above, there is a workaround: You can simply assign some keyboard shortcut to "rssguard.exe" in you operating system settings and if you hit the shortcut (and RSS Guard is already running and is hidden/minimized) then RSS Guard window will show-up.
