### ISSUE TITLE
focus changed when a feed get updated

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#46]
#### Brief description of the issue.

focus changed when a feed get updated. read a message from certain item and that item get updated, focus of the message changed to other message on the same item.

#### How to reproduce the bug?

1. select a message
2. update feed where you select the message
3. focus changed once update finished

#### What is the expected result?

hopefully focus still on the message that has been selected

#### What actually happened?

focus changed to other message on same feed item, which probably that a new message that just inserted into DB when update finished

**Comment by martinrotter** [comment]
This problem happens when:

1. You select some message from feed X.
2. You update feed X and new messages arrive.

Problem is that after the update is finished, the message list gets refreshed. And if you have message sorted from newest to oldest, then your previously selected message is moved down and the same index is selected.

So if your message was for example 4th from top, 5 messages arrived, so now your message is 9th from top, but 4th message is automatically re-selected after update, but now 4th message is different.

Problem is that you can have messages sorted via various columns, RSS Guard ignores this and just selects the same 4th message because it is faster.

I could fix this so that RSS Guard will really search for your previously selected message and select it, but there are more problems. RSS Guard would have to search through all messages in current feed and search for your message, which would be slow if there tons of messages in the feed. This will become even bigger problem if there is more than one msg selected.

I agree that current behavior is buggy and needs to be fixed. Question is, how? I can just remove the reloading of messages after feed update and user would have to (re)select the feed again and all msgs would be now shown. Or I can reload the feed and just select first message. Or I can reload the feed and do not select anything.

What do you think?

**Comment by blackarcher21** [comment]
Honestly I prefer this way

> RSS Guard would have to search through all messages in current feed and search for your message, which would be slow if there tons of messages in the feed.

But yeah, if that could slow down, that doesn't nice.

> This will become even bigger problem if there is more than one msg selected.

My concern is the message that currently being displayed. I don't select more message.

> Question is, how? I can just remove the reloading of messages after feed update and user would have to (re)select the feed again and all msgs would be now shown. Or I can reload the feed and just select first message. Or I can reload the feed and do not select anything.

Not sure. You might wanna check QuiteRSS. I just checked it and it keep last displayed message but don't know about performance with huge DB.

**Comment by martinrotter** [comment]
> I don't select more message.
Well, some other people might. What should app do if there is 5 msgs selected? Should it reselect all of them or just reselect currently visible (focused) message? I actually saw many apps which act like this, they just reselect one message and not all of them.

**Comment by blackarcher21** [comment]
> Well, some other people might. What should app do if there is 5 msgs selected? Should it reselect all of them or just reselect currently visible (focused) message? I actually saw many apps which act like this, they just reselect one message and not all of them.

Not sure, a bit confuse with technical. My opinion as common user is reselect currently visible (focused) message since its the one that been displayed on previewer and if possible, it doesn't intefere when reading.

**Comment by martinrotter** [comment]
That is true. I will fix this, so that if there is any message selected and displayed in previewer, then it will be reselected after the feed update again.

**Comment by martinrotter** [comment]
Please, test ef7afcc and let me know if bug is resolved.

**Comment by blackarcher21** [comment]
I would test but could you upload compiled version (high compression/7z)? sorry, because I can't compile as I don't have  all the requirements.

**Comment by martinrotter** [comment]
http://www.filedropper.com/rssguard-333-win32

**Comment by blackarcher21** [comment]
looks good, now it doesn't intefere reading when feed gets updated :+1: 
since select more than one msg doesn't open/show msg previewer, I think better it doesn't select anything doing multi-select. what do you think?

**Comment by martinrotter** [comment]
Well, it is tricky. When you select multiple items, then there is still one item with focus ("current item"). Maybe it would make more sense to display "current item" in previewer even if multiple messages are selected and then when you select multiple items -> update feed -> "current" item would get correctly reselected and would be visible again.

**Comment by blackarcher21** [comment]
yes, thats make sense in that way.

**Comment by martinrotter** [comment]
Yea, included the change in released 3.3.3 which came out today.
