### ISSUE TITLE
[BUG]: Unassailable Guard

### ISSUE THREAD

**Issue by sakkamade** [martinrotter/rssguard#466]
#### Brief description of the issue.

After RSS Guard is killed by `killall`, it cannot be started again.
(Although no RSS Guard instances may be found by `htop`.)

#### How to reproduce the bug?
1. ```bash
    $ killall rssguard
    ```
2. ```bash
    $ rssguard
    ...
    time="    14.408" type="warning" -> core: Another instance of the application is already running. Notifying it.
    time="    14.408" type="debug" -> core: Destroying Application instance.
    time="    14.408" type="debug" -> core: Destroying Mutex instance.
    time="    14.914" type="debug" -> gui: Destroying IconFactory instance.
    ```

#### What was the expected result?

To start application after it was killed (?)

#### What actually happened?

It does not seem to start again.

#### Other information

Here is the log. Clean first start in VB. Built with `debug` flag.
[rss-log.txt](https://github.com/martinrotter/rssguard/files/6987253/rss-log.txt)

(ran as `rssguard  > ~/rss-log 2>&1`; but there is nothing when running it with `--log <file>` likewise...)

* OS: Arch Linux, Xfce
* RSS Guard version: be051000b58cd7876005778552c5fd289f0afe02

**Comment by sakkamade** [comment]
Fixed. Thank you.

**Comment by martinrotter** [comment]
> but there is nothing when running it with --log <file> likewise

You mean that --log option does not actually produce log file?

**Comment by sakkamade** [comment]
No, it does. I meant that there is nothing regaring the time when I killed it.
It is doing exactly the same what `> ~/file 2>&1` do, right?

**Comment by martinrotter** [comment]
Yes, 99% the same. It is there primarily because of windows which likes to FUCK over GUI apps.

It is funny because on Windows, GUI apps cannot by default have their command line outputs redirected in built-in cmd.exe. Powershell behaves bit better but overally the experience is so messy that I had to add the switch.

**Comment by martinrotter** [comment]
btw the issue was fixed by stale "socket" file "/tmp/rssguard..." which was not removed when "enclosing" C++ object got killed, on every other OS (Windows, osx) relevant "resources" are automatically cleared when app is killed, but given that the socket on linux is actually a file, it was left behind.

**Comment by sakkamade** [comment]
> btw the issue was fixed by stale "socket" file "/tmp/rssguard..." which was not removed 

Yes, it is unfortunare to accept, but my only thought of the cause was the `/tmp/` directory... 
Would have never expected to learn to understand so much about any of it after moving to Linux...

**Comment by martinrotter** [comment]
In 15 minutes, I learned more about OS maintenance when installing Arch than year staying with Ubuntu.

Seriously, in Ubuntu I felt like the experience is not that good. Partly it was because crazy behavior of "apt-get" package manager which sometimes decided to do some crazy shit when resolving dependecies of a package, sometimes it just decided to delete shitload of packages which totally broke the system, sometimes graphics stopped to work properly etc. It is fair to say that those were Ubuntu 10.04 times, maybe novadays it is better.

Anyway I discovered Arch quite some years back and never looked back. The system felt so amazingly clean after installation and still feels the same today. Package manager is brutal, quality of packaging is somehow breathtaking when compared to Ubuntu. It is rolling-release but I have never ever had single major problem. Maybe once when they transitioned to systemd, I fucked something when migrating, but otherwise, it is fast, clean, smooth, very dev. friendly.

**Comment by sakkamade** [comment]
In second pharagraph you clearly described my experience with Manjaro KDE, from some months ago.

Ubuntu? I remember trying it a year ago in VB for some days, after which I set myself to never move to Linux. Hahaha.

**Comment by sakkamade** [comment]
> (...) after which I set myself to never move to Linux.

No, this is not quite a right way to word it,
"(...) after which I acknowledged that I will never _be able_ to move to Linux" is.
Since from what I heard at the time, it is considered the easiest Linux system to deal with, and the wisest choice for "newbies."

**Comment by martinrotter** [comment]
There is one thing which comes to my mind often.

Take Windows - huge user base, relatively good OS kernel, some great driver behavior, great support for all HW. The OS is missing one thing. Integrated package manager and strict packaging Linux-like approach. In other words, if Microsoft packaged every stuff and also greatly encouraged packaging for all applications, then the system would not be a mess over time. I see it everyday with enterprise users my company maintains. They have mess in their OS, junk everywhere, folders, files messed everywhere, no order, registry totally crapped with shit.

That is th reason Windows get slower and slower over time, no control over garbage.

**Comment by sakkamade** [comment]
> Integrated package manager and strict packaging Linux-like approach

When I first saw such thing in Linux, I thought "Ha?" since I compared it with Microsoft Store, with which I have never built a trust.
After I learned what it actually is and what it is for, I can but love it. Albeit now I do not even dare to compare them. 

> That is the reason Windows get slower and slower over time, no control over garbage

Hum, this is not quite it, but, in KDE, if I didn't clean some folders in `~/.cache` directory, I experienced great problems on regular basis, after updates, which were much worse than "get slower and slower", it used to just hang for whatever reason.
However, upon creating `systemd` service which removes  the `~/.cache` clean every shutdown, I had forgotten of such issues altogether. 

But I totally see your point. There is no way I would have removed the entire cache directory to "fix" Windows, it just don't have it.
