### ISSUE TITLE
[BUG]: Settings window is too big on high resolution / high DPI screens

### ISSUE THREAD

**Issue by fredddd1** [martinrotter/rssguard#493]
### Brief description of the issue

![windows-settings](https://user-images.githubusercontent.com/80743272/133216810-ff82669b-a9ac-4a53-a995-b302c5d6550d.png)

![settings-window](https://user-images.githubusercontent.com/80743272/133216791-5faf67db-1c33-436e-b4f1-352f039614e8.png)

### How to reproduce the bug?

Have a high resolution / high DPI device.

### What was the expected result?

For me to be able to see the entire window. Trying to resize the window to a smaller size is also not possible.

### What actually happened?

The window is too large.

### Operating system and version

* OS: Windows 21H1 64-bit
* RSS Guard version: 4.0.2

**Comment by martinrotter** [comment]
@fredddd1 Can window be resized manually to smaller size?

**Comment by fredddd1** [comment]
> @fredddd1 Can window be resized manually to smaller size?

Not possible.

**Comment by martinrotter** [comment]
@fredddd1 new dev. build is compilling possibly fixed your problem, wait 20 minutes and test latest development build pls.

**Comment by sakkamade** [comment]
@martinrotter, I am not sure what is the cause, but the Settings modal is broken for me now (Xfce):

![image](https://user-images.githubusercontent.com/62730422/133964044-3375c7dc-91b4-4053-8a2d-9d429577bf71.png)

Can you confirm, if you are seeing the same?

**Comment by martinrotter** [comment]
@sakkamade I wrapped the content area of settings dialog to "scrollable" widget and made default size of settings dialog bit smaller. If settings content are too big, scrollbars are displayed and you can scroll.

**Comment by martinrotter** [comment]
Also, "User interface" tab is the only which shows horizontal scrollbar by default, because the toolbar editor under "Toolbars" sub-tab is just too wide.

**Comment by sakkamade** [comment]
> you can scroll or make dialog bigger.

Yes, but the size is reset to this after I reopen it.

**Comment by martinrotter** [comment]
@sakkamade OK.

1a9514313

**Comment by sakkamade** [comment]
Perhaps resizable sidebar will also help?

**Comment by sakkamade** [comment]
> 1a95143

Works perfectly :heart:

**Comment by sakkamade** [comment]
I guess it should be said that to save current Settings window size, user must click either button "OK" or "Apply."

**Comment by sakkamade** [comment]
@martinrotter, Just a side comment.

I could look better with the scrollbar within, then I would not have thought that that is a bug, i.e. like so:
![image](https://user-images.githubusercontent.com/62730422/134102611-7e923581-8733-4263-b703-0a50ca77db2c.png)

While currently it looks thus:
![image](https://user-images.githubusercontent.com/62730422/134102421-3700c134-434b-4478-87fb-f42d1cc16ee9.png)

**Comment by sakkamade** [comment]
@martinrotter, While I was at it, I noticed something else, too. Here:

![image](https://user-images.githubusercontent.com/62730422/134129499-e007f845-980c-4f38-82f4-ff65890f1bea.png)

It has quite same issue.

Yes, I understand that this is perhaps a used-just-once window. 
But it is awful aesthetically, and can evoke complains plainly.

The OP having the issues with being unable to make the windows smaller, it is not that they __must__ be smaller.

Although ability to resize window to make it smaller may be useful, it is not the reason making them such by default.

Perhaps all the windows can be restored to their hardcoded, former size (with the size that is as small as possible for scrollbars to be invisible)?
(Although I think that the ability to save the size should be left for Settings window.)

**Comment by martinrotter** [comment]
Yes, I need to go through all windows and resize initial sizes to avoid scrollbars. Will fix this one. Hopefully there are not others.

**Comment by martinrotter** [comment]
e9add2fd7

**Comment by martinrotter** [comment]
> 
> 
> @martinrotter, Just a side comment.
> 
> It could look better with the scrollbar within, then I would not have thought that that is a bug/regression, i.e. like so:
> ![image](https://user-images.githubusercontent.com/62730422/134102611-7e923581-8733-4263-b703-0a50ca77db2c.png)
> 
> While currently it looks thus:
> ![image](https://user-images.githubusercontent.com/62730422/134102421-3700c134-434b-4478-87fb-f42d1cc16ee9.png)

Yes, this is something in the GUI library I use and did not find a way to fix downstream.

**Comment by sakkamade** [comment]
https://bugreports.qt.io/browse/QTBUG-96765
> Force border around scrollbar in QScrollArea

Is it really?
I don't think it is that the border should be around the scrollbar, it is that the scrollbar should be within that sub-window, i.e.:


https://user-images.githubusercontent.com/62730422/134289460-27bcad8c-1c23-40e2-9c34-8471d5a81dc1.mp4

Or am I missing something?

**Comment by martinrotter** [comment]
Yes, you are. There is a generic "scroll area" control which automagically decides if to show scrollbars or not and the control is created automatically for each settings page, no matter what is actually on the settings page. In your case what is misleading you is that there is "tab" control which also introduces yet another frame/border.

In other words, controls/widgets (like tab control) are not normally "scrollable" in both directions, you must create extra (scrollable by design) control and include tab (control to be actually scrolled with) inside it. It is a bit complicated to explain for non-programmers.

The only problem is the appearance of "scroll" control. I can force border and the part with scrollbar looks better, unfortunately the parts of widget (top/left) is just weird.

![image](https://user-images.githubusercontent.com/1255302/134290774-10d559fd-804b-4acb-9706-c1b2d07c99fa.png)

**Comment by martinrotter** [comment]
@sakkamade Does this look better?

![image](https://user-images.githubusercontent.com/1255302/134292122-229accd6-ad5b-4828-9a68-86389f997bd3.png)

**Comment by sakkamade** [comment]
> which also introduces yet another frame/border.

Yeah, that thought took only a second place in my head, thought. As it looked too neat to me.

> Does this look better?

It does, but here: https://github.com/martinrotter/rssguard/issues/493#issuecomment-924610789 :wink: 


Also, does the sidebar truly needs to be so wide? I tried couple of different locals, and it appears to me that it may certainly be more narrow, more so if the line "Web-browser and e-mail..."  were to be renamed.

**Comment by sakkamade** [comment]
> The only problem is the appearance of "scroll" control. I can force border and the part with scrollbar looks better, unfortunately the parts of widget (top/left) is just weird.

**Comment by martinrotter** [comment]
@sakkamade Pushed cfdd6f0b1.

Test when it builds and let me know if that is what you think is generally better.

**Comment by sakkamade** [comment]
Overall yes, better, yes.

The scrollbar in  "Keyboard shortcuts" and "Notifications" can also be moved to the right border, I guess.

I have tried it with some different styles, and the best experience was with "Windows" style. I don't like it, though.

**Comment by martinrotter** [comment]
>The scrollbar in "Keyboard shortcuts" and "Notifications" can also be moved to the right border, I guess.

Yes, those controls will need to be tweaked a bit. So overall improvement? OK, will polish it.

**Comment by martinrotter** [comment]
5237ee313

**Comment by sakkamade** [comment]
Great! It looks rather neat now. f0ad4ff4

Although, of course, there are still some ~~nitpicks~~ suggestions:

<details><summary>Spoiler</summary>

### 1

Would  white background look better on such pages?
![image](https://user-images.githubusercontent.com/62730422/134570082-4804bc54-53f3-48e5-a27b-3d33c87b8b12.png)

### 2

Too much of free space is left in some tabs of "UI" section:


![image](https://user-images.githubusercontent.com/62730422/134570516-f8a496d2-c5d9-402e-890e-0cb4f8074b1a.png)

But I am not sure  whether it is possible (needed?) to change only for certain tabs, since it is likely due to this tab having these widgets:

![image](https://user-images.githubusercontent.com/62730422/134570650-dcb538eb-ce02-4d5f-9758-902a0631ab77.png)

Only called your attention to it.

</details>

**Comment by sakkamade** [comment]
Is it possible to remove that  second white border? (RSS Guard is on the right.)
![image](https://user-images.githubusercontent.com/62730422/134791745-ee6f5cbb-0e0f-4de8-9b6e-d39bbe92656e.png) ![image](https://user-images.githubusercontent.com/62730422/134791725-8d33d114-b668-4b58-80f1-552ef1a754e6.png)

---

Also, perhaps the Settings can be moved around a bit, so as to remove the tabs?

For example, "Tray area" tab may easily be moved from UI to Notifications and still don't look out of place. 
"Toolbars" deserve their own section, is what I think.
And everything else—"UI", "Feeds and Articles" and "Web browser and e-mail"—can be flattened to single vertically scrollable widgets, since they are scrollable now.

**Comment by martinrotter** [comment]
As for "tabs", it is not possible to force scrollbar only for one of tabs (technically it is possible, practically, to cumbersome).
As for reorganization of some settings/tabs. Yes, that is something that would make sense. Perhaps create separate article for it, @sakkamade.

**Comment by martinrotter** [comment]
About "Is it possible to remove that second white border? (RSS Guard is on the right.)"

What border, where exactly that screen snippet comes from?
