### ISSUE TITLE
[FR]: Multipage pop-up notification window with titles of new posts

### ISSUE THREAD

**Issue by GeniusBroccoli** [martinrotter/rssguard#499]
### Brief description of the feature request

Hi. I would love to see a more informative pop-up notification of new posts. In QuiteRSS popup shows titles of the new messages for each channel. And it's multi-page, in case there are a lot of posts at once. It's also customizable, the number of posts per page, icons, etc. Also, if you put the cursor on it, it does not disappear, allowing you to view everything. Very useful when you need to see the news as soon as it appeared during work (I have some channels polled every two to five minutes).

**Comment by martinrotter** [comment]
I see, that is something I was thinking about "porting" from QuiteRSS.

**Comment by sbstn87** [comment]
I second the feature request. The QuiteRSS notification combines usefulness and looks and I think is the best one among RSS readers:
https://quiterss.org/sites/default/files/screenshots04_0.png

That's one thing I miss the most after I started to use RSS Guard.

**Comment by expg** [comment]
> I see, that is something I was thinking about "porting" from QuiteRSS.

I just signed up on Github to just say this.
I've been using QuiteRSS for years because it's the only RSS reader including web-based that offers a multipage notification popup.
And it's the only reason why I still can't abandon QuiteRSS and switch to RSSGuard.
RSSGuard already offers better features than QuiteRSS but it's all about UX(User Experience) design.

Imagine you have 20+ feeds and you're receiving 100+ articles per hour, how can you handle it all?
Not all the articles are worth reading so we have to filter out most of them.
But if you do that with your eyes, one by one, then the whole point of using an RSS reader is simply gone.
So we need a proper article filtering feature and it should be displayed in a multipage notification popup.
A filtering criteria is never perfect, human filtering is still needed, multipage notification popup allows you to do that without a single click.
In the end, you can do the whole process without a single click. that's why the customizable rich notification popup is an essential feature combined with the article filtering feature.

RSSguard currently offers javascript based article filtering but using a simple balloon popup limited it to not fully utilize its feature. thus you need a few more clicks than QuiteRSS.
I hope RSSguard inherits the multiplage notification popup feature from QuiteRSS since it's no longer maintained.
Thanks.

**Comment by martinrotter** [comment]
already implemented in latest version
