### ISSUE TITLE
stop running update doesn't seem working

### ISSUE THREAD

**Issue by blackarcher21** [martinrotter/rssguard#52]
#### Brief description of the issue.

Stop running update doesn't seem working to me. Windows 8.1 x64, RSS Guard 3.3.3

#### How to reproduce the bug?

1.  Running update on certain feed/category
2.  Stop running update by click button on toolbar/status bar/via menu

#### What is the expected result?

Running update is stopped

#### What actually happened?

Update keep running until finished

**Comment by martinrotter** [comment]
Yes, I have observed this issue. Working on it.

**Comment by martinrotter** [comment]
Actually, the feature works. Problem is when you hit "update feeds". Each feed's update is immediately started in its own thread and all feeds download their new message simultaneously/in parallel. This action cannot be interrupted. When some feed finishes downloading of messages, then those messages are saved into DB, saving is NOT parallelized and is done synchronously in main thread. This action can be interrupted.

So the phase where feeds are all started and downloading cannot be interrupted. I will make some enhancements to make "stopping" faster IF POSSIBLE. But in general, stopping of feeds update will not work fast. This is by design and is caused by recent new feature - feed parallel updates.
