### ISSUE TITLE
with ownCloud account not possible to mark as READ

### ISSUE THREAD

**Issue by okias** [martinrotter/rssguard#62]
#### Brief description of the issue.

Setup owncloud account, loaded articles and 
#### How to reproduce the bug?

1. SQLITE in memory
2. setup Nextcloud (10) account
3. read message, message not going to change as "read" and it's not possible force it
4. 

#### Other information (logs, see Wiki)
[rssguard] ownCloud: Marking messages as (un)read failed with error 401.
  Type: WARNING
  File: /build/rssguard-IcmDF2/rssguard-3.2.4/src/services/owncloud/network/owncloudnetworkfactory.cpp (line 345)
  Function: QNetworkReply::NetworkError OwnCloudNetworkFactory::markMessagesRead(RootItem::ReadStatus, const QStringList&)

**Comment by martinrotter** [comment]
Update to 3.3.5 and let me know if bug is solved.

**Comment by okias** [comment]
sadly, PPA I use has latest 3.2.4, in Download resources I don't see any point to PPA or .deb package. Where can I get latest build?

**Comment by martinrotter** [comment]
I used to build Debian deb packages in my OBS but I stopped it because it was to difficult for me to maintain (I do not run Debian distro.).

So you will have to make packages by yourself for Debian now.

Also, you need to re-add Owncloud account again in new version to fix this problem.

See #59 for more.
