### ISSUE TITLE
[FR]: New tabs work or not

### ISSUE THREAD

**Issue by GeniusBroccoli** [martinrotter/rssguard#654]
### Brief description of the feature request

Hi. I couldn't find a better way than to write here. I can't understand, judging from the settings, the ability to create tabs is there, but how to do it? I've looked through the context menus and I don't see the right section. Thanks.

**Comment by martinrotter** [comment]
What do you mean by tabs?

**Comment by GeniusBroccoli** [comment]
> What do you mean by tabs?

Several separate tabs for feeds/accounts, like in a web browser? No?
![678678687](https://user-images.githubusercontent.com/18056785/155878959-fe5a3d53-937d-45e7-9904-e8afad5631ad.PNG)

**Comment by akinokonomi** [comment]
> Several separate tabs for feeds/accounts

@GeniusBroccoli In RSS Guard, tabs are not used for that.

There are multiple other use cases, including:
- Open the Newspaper view by double clicking the feed name in feed list
- Open the URL of article (the web page is opened in new tab) (nowebengine version is not supported)
- Create a new web browser tab with Ctrl+T (nowebengine version is not supported)

> P.S. nothing happens when I double-click on the tab bar, if this is tab bar ... 

You should not double/middle click the tab _bar_, instead, according to settings, you should double click the tab itself to close it, though the Feed tab cannot be closed.

**Comment by akinokonomi** [comment]
> P.S. nothing happens when I double-click on the tab bar, if this is tab bar ... 

Well, this one does not work for me too (cc103710).

**Comment by martinrotter** [comment]
> > P.S. nothing happens when I double-click on the tab bar, if this is tab bar ...
> 
> Well, this one does not work for me too ([cc10371](https://github.com/martinrotter/rssguard/commit/cc1037102905877c89c7e0612e5c5b755e25984d), both Qt5 and Qt6 builds).

Yes, this is because I switched [this](https://doc.qt.io/qt-5/qtabbar.html#documentMode-prop) to `false`. I will switch it back to `true` but mind that this also affects the appearance of tab-bar a bit. The property had `true` for a long time, then I switched it (but don't remember [why](https://github.com/martinrotter/rssguard/blame/9d0d8ce14e825d3290fe8e5a4efc88f050d5b856/src/librssguard/gui/tabbar.cpp)). Without the property being true, the "double-click-empty-space" feature is not possible.
