### ISSUE TITLE
[BUG]: #7f5d1473 has borked account and sync

### ISSUE THREAD

**Issue by umbellipher** [martinrotter/rssguard#655]
### Brief description of the issue

Updated to #7f5d1473. On starting, settings appear in place, but it had no recollection of my Bazqux account, and asked for my credentials.

On setting it up again and logging into it, sync doesn't happen.

Restart chucks my account out again.

### How to reproduce the bug?

See above.

### What was the expected result?

See above.

### What actually happened?

It didn't: see above.

### Operating system and version

* OS: Windows 10
* RSS Guard version: #7f5d1473

**Comment by martinrotter** [comment]
You have "devbuild" version installed, I suppose and you upgraded to newer "devbuild". Quoting devbuild release page:

> These development builds are here for EXPERIMENTING. Things will break and your data will burn in hell. You have been warned!!!

Individual "devbuild" testing releases are NOT guaranteed to be cross-compatible between each other and that incompatibility happened now because of [this](https://github.com/martinrotter/rssguard/commit/7f5d1473a3b28e3baa99b51523b1e12eac1e177c#diff-e9745cd95218604b151a5c53e0f59e47f10abdd5450e405544867a14348ee7fb) change.

Your DB schema has version "2" but this version saw several DB changes which I incorporated gradually. You need to tweak your tables manually - namely add missing `ordr` columns and populated them as copy of `id` columns.

Users who use stable releases will not be hit by this behavior as currently stable DB schema version is 1 and will get auto-updated to "full" 2 when users upgrade from rssguard 4.1.2 to 4.2.0.
