### ISSUE TITLE
[FR]: Article filters Help

### ISSUE THREAD

**Issue by fulige18** [martinrotter/rssguard#677]
### Brief description of the feature request

You are the most frequently updated RSS reader developer I have seen since 2022, I admire you very much. But some functions of the reader are really difficult to get started. For example, in this article filtering, although you provide helpful instructions, it is really difficult to edit for those of us who do not have a code base. If I have time, I really hope to have a simple filter setting method like QuiteRss or Feedbro.

**Comment by fulige18** [comment]
![QQ拼音截图20220406142905](https://user-images.githubusercontent.com/100845677/161909833-2b4f74f6-8975-4530-b326-98eed311c442.png)
![QQ拼音截图20220406143021](https://user-images.githubusercontent.com/100845677/161909834-2b2c12ae-6068-4c6b-b1ef-e1fb0c32ad51.png)

**Comment by martinrotter** [comment]
It is quite unlikely for me to implement this. What I could do is to add more examples into documentation.

**Comment by fulige18** [comment]
> It is quite unlikely for me to implement this. What I could do is to add more examples into documentation.
It's a pity, after all, this function is very important, I think some rss users may be discouraged by the current filtering method。

**Comment by Owyn** [comment]
I too find filters rather confusing to use, you have to go to filters, uncollapse every subfolder manually and match the filter with the feed

instead of going full-simpleness if you so do not want it - you could just maybe just change the UI for current script filters and prepackage few default ones - e.g. blacklist one and whitelist one and give shortcuts to use them right from the feed editing window? would be simple for the users and literally same functional as now (but more handy)

here's what I was going to suggest (but then I've found this issue)
![new_add_edit_feed_design](https://user-images.githubusercontent.com/1309656/162636689-1c9619ad-147c-4d6a-8e91-2a435e7dc999.png)

**Comment by martinrotter** [comment]
Reaction to the picture:

* You do not have to "really" select feed type/encoding, all these are automatically selected if yout hit "Fetch it (metadata) now" button.
* Collapsible textboxes -> makes sense, might implement it.
* As for filters. I admit that learning curve is very steep. I might add filter script "generator" - simple wizard which will allow user to select type of filter (whitelist, blacklist, conditions, etc.) and "generate" the script code for the user. After it is generated, user should see and understand the structure of filter more easily.

**Comment by Owyn** [comment]
> * ou do not have to "really" select feed type/encoding, all these are automatically selected if yout hit "Fetch it (metadata) now" button.

yea, that's the thing, that's why it is confusing.

> "generate" the script 

well, generating it is one thing (thought all basic filters could be just pre-shipped)

but the main thing is using filters, I already have all my filters, and making filters for new feeds just makes me copy-paste stuff (along with lots of clicks in the filters window)

I just want to click "edit feed" on my feed and set up the filter there without going anywhere far, or to edit it by just adding one more title to the whitelist real quick

**Comment by martinrotter** [comment]
> yea, that's the thing, that's why it is confusing.

sometimes the autodetection fails

> but the main thing is using filters, I already have all my filters, and making filters for new feeds just makes me copy-paste stuff (along with lots of clicks in the filters window)

Well, you can have one filter shared for many feeds. Not sure what you ask here. :)

**Comment by Owyn** [comment]
> Well, you can have one filter shared for many feeds. Not sure what you ask here. :)

filters as scripts

Yes, I basically have just one filter for everything to whitelist by title, I just make different titles for each feed (params for that filter), so now I have to make a filter for each of my feeds instead of having one filter script and just passing params to it from a quickly-accessible place (add\edit feed window)

**Comment by jediafr** [comment]
On this very topic, is there somewhere we can discuss, exchange more examples of filters.
I'm fluent in shell but js is another beast and i'm struggling to get something as simple as moving articles around, or even applying an existing label

**Comment by martinrotter** [comment]
https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#examples

also, visit us on discord, see top part of docs for link or readme

**Comment by jediafr** [comment]
yep sorry i've just noticed the discord. I've asked there.
