### ISSUE TITLE
[FR]: Delete keyboard shortcut

### ISSUE THREAD

**Issue by catthou** [martinrotter/rssguard#747]
### Brief description of the feature request

Help, I thought I was deleting keyboard shortcuts but I accidentally keybound every single action to `Esc`

There's also no "delete this keybind" in the right-click context menu.

I am using the RSS Guard 4.2.3 appimage on Linux

**Comment by akinokonomi** [comment]
I guess I'm a bit late, but you can simply delete the whole `[keyboard]` section in `~/.config/RSS Guard 4/config/config.ini`.
I just tried it myself and it went without a hitch. 
Do a backup first though, just in case.

**Comment by martinrotter** [comment]
![image](https://user-images.githubusercontent.com/1255302/179386474-e8f34548-dda3-4ac1-9882-566c42b3ab85.png)

Is this what you wanted but maybe missed it?

**Comment by catthou** [comment]
That's exactly what I wanted!  I had no idea there were buttons there because my "default" and "system icon theme" both don't display any icons except the adblock icon. See:
![220717-142609 AppRun](https://user-images.githubusercontent.com/5198243/179425547-e780b7cb-1bb6-4ac3-83c3-8290d14832e2.png)

But I've observed something: the primary button bar has text alternatives when there are no icons in the chosen icon theme, see this comparison -
Adwaita icons:
![220717-143429 Selection](https://user-images.githubusercontent.com/5198243/179425600-8ef85f27-d843-4fbd-a2de-bf857c6856a2.png)
System theme/no icons:
![220717-143445 Selection](https://user-images.githubusercontent.com/5198243/179425900-5a013234-55a1-4ec2-97c3-112eaabe66c7.png)

But the buttons on the keyboard shortcuts page don't, they're just invisible. So, questions:
1. Is it possible to add text if there is no icon?
2. If you can't add text, would it be prudent to include a pair of icons for these buttons in case icons were not found in the selected icon theme?

**Comment by akinokonomi** [comment]
@catthou Oh I see, so that what the problem was. 

Well, RSS Guard officially supports Breeze and Numix icon themes. (They are also shipped with Windows build at the moment.)
And though Faenza, Papirus, HighContrast (with few icons missing), and some other should work without a problem too, it is not the case with at least Adwaita and hicolor. 

I see at some point Martin removed few button hints that were there for when user had incompatible icon theme, like in toolbar settings.

| Before | After
| --- | ---
| ![image](https://user-images.githubusercontent.com/91767492/179590138-2a9bc6c0-61a5-4848-8401-ddd347683aa5.png) | ![image](https://user-images.githubusercontent.com/91767492/179588391-2feb5c96-7a9e-4166-9fdf-5ac69bf60337.png)


Therefore, I think RSS Guard won't support such corner cases anymore in favour of simplistic look. (@martinrotter Please correct me here if it is not so.)

So, you can either fill in a report to your distribution bug tracker to add one of supported icon themes as optional dependency for RSS Guard, or just install one yourself.

The icon theme can be changed in RSS Guard settings (User interface -> Icons & skins -> Icon theme).

**Comment by martinrotter** [comment]
37ba26931

**Comment by akinokonomi** [comment]
> [37ba269](https://github.com/martinrotter/rssguard/commit/37ba2693117f6fdcf04079c24e0f4361b856c704)

Well, should've worked just fine, only Breeze icons look kind of fuzzy:

Natively installed icon theme:
![image](https://user-images.githubusercontent.com/91767492/180070789-e0b3e858-6cf9-4802-ae22-a9f87461f4a7.png)

Icons shipped with AppImage:
![image](https://user-images.githubusercontent.com/91767492/180070678-57c09e57-9821-4850-87d2-8d240048b348.png)

Both screenshots made using the same AppImage.

**Comment by catthou** [comment]
I don't see any problem with including breeze icons, and I'm not having any issues with the latest development build.
