### ISSUE TITLE
[Feature request]: Open URL in external browser without confirmation

### ISSUE THREAD

**Issue by luigino** [martinrotter/rssguard#76]
It would be nice to have a setting so that links would be opened directly with the default handler without having to confirm.

No biggie, but I suspect many would like such a feature.

Thanks

**Comment by martinrotter** [comment]
So you use RSS Guard version with classic text-based component for message viewing. This component cannot open weblinks in new tab because there is no way to display them, therefore there are currently two options:

- open links in external browser,
- save HTML of the link to hard drive.

Note that Chromium-based version of RSS Guard offers other two variants:

- open links in new tab (`CTRL+CLICK` on any link),
- save HTML of the link to hard drive.

I guess I can make the dialog go away once user makes such a choice in the app settings.
