### ISSUE TITLE
[FR]: Web view in dark mode

### ISSUE THREAD

**Issue by norman003** [martinrotter/rssguard#818]
### Brief description of the feature request

![image](https://user-images.githubusercontent.com/33376952/195103425-5607c039-a169-4796-89d9-8ebf7339790e.png)
When you clicked in url
![image](https://user-images.githubusercontent.com/33376952/195103499-72c3fecf-e808-4ddb-8d75-4f93e6f7ea3c.png)
In brave I use Dark Reader
https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

**Comment by guihkx** [comment]
I think you want a *forced* dark mode, no? At least that's what Dark Reader does.

Because as of today, the BBC News website doesn't have *proper* dark mode support, which is through [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

Nevertheless, on websites that *do* support `prefers-color-scheme`, I feel like this should be working (as of QtWebEngine 6, anyway), but it isn't:

![image](https://user-images.githubusercontent.com/626206/196258770-8cecc83b-d6cf-49b7-8320-e0e123e3f60c.png)

The workaround is to create an [environment variable](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html) called `QTWEBENGINE_CHROMIUM_FLAGS` and set its value to `--blink-settings=preferredColorScheme=0` ([`0` = dark, `1` = light](https://chromium.googlesource.com/chromium/src/+/9a69785f81c63534ca6526e4a3fb2b162d9763cb/third_party/blink/public/mojom/css/preferred_color_scheme.mojom)):

![image](https://user-images.githubusercontent.com/626206/196259492-3d3308f1-04d2-4c3a-ab38-3c546d338606.png)

After that, close RSS Guard, clean its WebView cache (by deleting  `%LOCALAPPDATA%\RSS Guard 4\web\cache`), and then proper dark mode through `prefers-color-scheme` (on websites that support it) should work. 

![image](https://user-images.githubusercontent.com/626206/196260289-361a29d8-023f-4c66-a604-bea4444d4a0c.png)

Now, for *forced* dark mode, you can append the `forceDarkModeEnabled=true` preference to `--blink-settings`, i.e.:

`--blink-settings=preferredColorScheme=0,forceDarkModeEnabled=true`

Now all websites will have a forced dark mode:

![image](https://user-images.githubusercontent.com/626206/196261417-f576ca00-8fc1-4bcb-b832-b2623e049233.png)

Just keep in mind that forced dark mode can break the layout in some websites.
