### ISSUE TITLE
[FR]: Add more custom skin color overrides

### ISSUE THREAD

**Issue by xmstspider** [martinrotter/rssguard#838]
### Brief description of the feature request

Hi,

I would like to override skin colors of folders/feeds in the left TreeView. I saw #711 but unless it would be implemented soon, by using the default "nudus-dark" skin, the only difference between unread and read items is by text boldness.

See my screenshot below - the visual difference between e.g. Automation and Containers is almost none. Yes there is an unread items counter to the right, but I would like to make them visually different.

![screen](https://user-images.githubusercontent.com/7497125/201204716-f942386d-282d-4aad-9d00-fa3a0d8960c7.png)

Is this something which could be done easily or is it complicated?

Thank you

**Comment by martinrotter** [comment]
@xmstspider Well, at this point "interesting stuff" color is used when NEW articles arrive. It is not used when you have UNREAD not newly fetched articles.

Also, the coloring is only applied to feed nodes in the feed/category tree.

So two things:
* [ ] - make sure that "interesting stuff" color applies for ALL unread feeds.
* [ ] - make sure that the color is also applied to ALL unread feed tree nodes, not just feeds.


I implemented the first sub-fr now.

![image](https://user-images.githubusercontent.com/1255302/201277095-e1bf86cb-bf29-42d8-a0bc-dd61e374c070.png)

**Comment by akinokonomi** [comment]
> make sure that "interesting stuff" color applies for ALL unread feeds.

@martinrotter Are you certain it's the right thing to do here? In my opinion, it's important to have them separated.

> See my screenshot below - the visual difference between e.g. Automation and Containers is almost none

@xmstspider I'm not sure I understand. The difference is quite plain to me.

If you want it to be better noticeable, did you try setting "Hide article counts if there is no unread articles" in Settings -> Feeds & Articles -> Feeds list?
You can also play around with "Article count format". For example, setting it to `%all - %unread` or just `[%unread]`.

---

@martinrotter Maybe, instead of new colors, it would be better to introduce some sub-icon/emblem over the item icon. 
Something like this?

![image](https://user-images.githubusercontent.com/91767492/201545530-d66b3631-c103-4872-bd6c-eaf563f89e4b.png)


Because I don't think many users would care to have a rainbow out of the feed list, or configure/re-configure dozens of different colors in the settings. (What is suggested in #711)

**Comment by martinrotter** [comment]
> Are you certain it's the right thing to do here? In my opinion, it's important to have them separated.

Fixing this RN. Adding extra "new-articles" override. Will add more overrides soon.

**Comment by martinrotter** [comment]
1e28d482f

closing, seel the other bug ticket for more info in the future
