### ISSUE TITLE
Warning about a depricated function: Document.defaultCharset

### ISSUE THREAD

**Issue by groentebroer** [martinrotter/rssguard#85]
#### Brief description of the issue.

To avoid breaking stuff in the future, in the log a component complains about:
[rssguard] WARNING: 'Document.defaultCharset' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6217124578066432 for more details.

#### How to reproduce the bug?

1. Problem occurs after a while, seems to be viewing or updating a new item.

#### What is the expected result?

No Warning

#### What actually happened?

This warning in the log.

#### Other information (logs, see Wiki)
Edit: Thinking about it, this could be the result of the content as well?

**Comment by martinrotter** [comment]
Yes, this is mostly probably caused by the actual contents of those messages. RSS Guard does not use that HTML tag for displaying messages anywhere, but it is specified by Qt framework.

When new Qt is released, they will for sure remove all deprecated calls. Thus, this is not our bug, but bug upstream.
