### ISSUE TITLE
[BUG]: Problem opening feed in system web browser

### ISSUE THREAD

**Issue by peter099** [martinrotter/rssguard#851]
### Brief description of the issue

When i click the button 'Open this website in system web browser' RSS Guard won't open feed source web page, but instead it opens feed aggregator page.

### How to reproduce the bug?

1. Click on a feed title.
2. Click the button 'Open this website in system web browser'.
3. It opens the url 'http://feeds.feedburner.com/' instead of the feed source.
4. Screenshot: https://i.imgur.com/VaVVWOT.png

### What was the expected result?

To open the feed source page in my external browser.

### What actually happened?

Instead of feed source page url it opens this url: http://feeds.feedburner.com/

### Debug log

[rssguard.log](https://github.com/martinrotter/rssguard/files/10146013/rssguard.log)

### Operating system and version

* OS: MX Linux
* RSS Guard version: 4.2.5 (flatpak version)

**Comment by martinrotter** [comment]
This is a feature and has purely technical reasons.

Some feeds contain RELATIVELY referenced resources (images, videos). In order to load these relatively referenced resources, RSS Guard has to use base address as "source address" of an article.

If you want to open URL of article, click on blueish "URL" text.

**Comment by peter099** [comment]
If i click on the blue url text it loads the website page inside RSS Guard, it's not opening the page in my external browser.
