### ISSUE TITLE
[BUG]: Mastodon feeds don't show Titles but instead just ID's

### ISSUE THREAD

**Issue by RonnyTNL** [martinrotter/rssguard#919]
### Brief description of the issue

Mastodon feeds lack a Title field, and hence don't display anything readable in the Title column, can this be improved?

![image](https://user-images.githubusercontent.com/19427356/233623560-2cefd8b6-3550-4342-97fb-954d0a3bc76e.png)

![image](https://user-images.githubusercontent.com/19427356/233623790-f9e76180-f73f-4019-a88a-f88ba0eb2b93.png)

Sample URL Feed:
https://mastodon.social/@campuscodi.rss

### How to reproduce the bug?

1. Import feed
2. Fetch feed

### What was the expected result?

Would be nice if it could somehow show readable content in the Title field so you can "scan the titles" while going over a bunch of new feeds.

### What actually happened?

Shows only ID's

### Debug log

<no log>

### Operating system and version

* OS: Win10x64 22H2 
* RSS Guard version: 4.3.4 - Stable

**Comment by martinrotter** [comment]
Yes, well. This is because those feeds are clearly broken, so I do not want to add some general option for all users. Instead, here is simple article filter to fixup the feed. Simply assign the filter to the feed and run "Process checked feeds" and it will convert existing articles + will automatically convert all new fetched articles in the future.

```js
function filterMessage() {
  var plain = msg.contents.replace(/<[^>]+>/g, '');
  msg.title = plain.substr(0, 48) + "...";
  return MessageObject.Accept;
}
```

Result: 
![image](https://user-images.githubusercontent.com/1255302/233932816-937a145c-c5a3-464a-82f7-cdff33bbc805.png)
