### ISSUE TITLE
[BUG]: The last line in the paragraph before the image has a huge paddings

### ISSUE THREAD

**Issue by GeniusBroccoli** [martinrotter/rssguard#924]
### Brief description of the issue

I do not know how to accurately explain, in general, in some news, images are somehow improperly embedded in the text, like pulling away the last line of the paragraph behind itself. I suspect that this is related to the figcaption tag.

### How to reproduce the bug?

For example, I see a lot of this kind of stuff in the ghacks feed: https://www.ghacks.net/feed/

### What was the expected result?

Images are neatly embedded in the text in separate blocks.

### What actually happened?

See description.

### Debug log

I havent.
![Снимок](https://user-images.githubusercontent.com/18056785/233842554-abe89972-deab-4952-99d0-a5ac2361fe0f.JPG)

### Operating system and version

* OS: Windows 7
* RSS Guard version: 4.3.4

**Comment by martinrotter** [comment]
Yes, this behavior is unfortunately there because of clumsy "rendering" by "non-web-engine" HTML component. Particularly it has problems with too big inline pictures. So it is upstream issue, not our bug.

I recommend to limit height of images in settings which kind of fixes the problem.

![image](https://user-images.githubusercontent.com/1255302/233930062-f9c4c0dd-b26b-487f-bbc3-5774305e678d.png)

Then it looks like this.

![image](https://user-images.githubusercontent.com/1255302/233930096-fc57a9d4-40ad-4354-ab19-868fc4181ffc.png)

Note that you can click or CTRL+click any picture and it will be opened either in new tab or in external browser.
