### ISSUE TITLE
[FR]: Read state as an icon, in addition to font boldness

### ISSUE THREAD

**Issue by birdie-github** [martinrotter/rssguard#948]
### Brief description of the feature request

Currently it's hard to differentiate between read and unread articles at a glance.

Here's what I'd do:

For the column "Is this read?" - remove the feed icons from it and merge icons with Titles.

This column could instead have two states: no icon (e.g. read) and an icon of your choice (unread article). So it would be like this:

```
Important      Read_State    Title
[❗ or empty ] [🟢 or empty] [Feed_icon: Article_name]
e.g.
                🟢            🚓 New Chevrolet SUV released
❗                            🚓 Lexus increased its market share in India
```

Now when you sort by the Read_State column, it's easy to see which articles are read and which are not. You've got a green circle for unread ones.

**Comment by akinokonomi** [comment]
> For the column "Is this read?" - remove the feed icons from it 

That's actually the feature that is disabled by default.
See Settings -> Feeds & articles -> Articles list -> Display real icons of feeds instead of read/unread icons

By default, the Read column has an icon in it that changes depending on read state.
The icon style depends on icon theme you chose.
Breeze icon theme looks nice.

If you have hard time telling apart read and unread articles, you could try making rows bigger in Settings -> Feeds & articles -> Articles list -> Row height.
You could set it to something like 26.
And you can make the font a little bigger just for article list too.

**Comment by Rex000** [comment]
I think he wants to have both at the same time which is okay.  However if this is implemented, the ability to turn feed icons on/off should stay.

**Comment by Rex000** [comment]
I think he wants to have both at the same time which is okay.  However if this is implemented, the ability to turn feed icons on/off should be provided separately.

**Comment by martinrotter** [comment]
There is also "Article highlighter" action which you can add to article toolbar which also marks unread (or important) articles with color.

**Comment by martinrotter** [comment]
Added feature, switchable in settings -> feed & messages -> feed list -> unread article icon type.

![image](https://github.com/martinrotter/rssguard/assets/1255302/87fd8e9a-9aea-4aa7-a87b-aaaf3610998b)

**Comment by Rex000** [comment]
IMO feed icon and read/unread dot icon should have their own separate columns.
