### ISSUE TITLE
[Rant]: Navigation, reading and handling

### ISSUE THREAD

**Issue by birdie-github** [martinrotter/rssguard#949]
### Brief description of the feature request

I'm talking as a long time user of Akregator and QuiteRSS.

Navigation and articles reading/deletion seem completely broken in RSSGuard:

Here's my normal workflow:

1) Use 'Ctrl + Up/Down' to navigate through feeds
2) When you choose a different feed, the article at the top gets selected and shown automatically
3) You can then press 'Up' or 'Down' to navigate through articles
4) Pressing 'Delete' deletes the current article
5) Pressing 'Ctrl + Delete' or 'Ctrl + A' followed by 'Delete' deletes all the articles for the current feed

Let's talk about RSSGuard:

OK, I navigate though feeds using 'Up' and 'Down'.

When I press 'Delete' it offers to delete the current feed! Woah, wait a bit, people rarely if ever do that and right mouse clicking and choosing "Delete the Feed" sounds a ton more rational.

OK, is there anything to change the focus to the first article in the feed? I've clicked everything possible including 'Space, Enter, Ctrl Enter, Right/Left Arrows, Ctrl + Arrows', nothing works.

Oh, 'Ctrl + Left/Right' expand and compact the current feed folder. Interesting. I can imagine people rarely if ever do that using keyboard.

Is there a shortcut to mark read all the articles for the current feed? Oh, I've just marked read all the articles for all the feeds. Bummer.

OK, I admit it I don't know what to do.

OK, let's try to delete articles. They are now struck through. Why don't they disappear right away in the Recycle Bin? Oh, can I disable the whole Recycle Bin feature? Nope.

So for keyboard:
* I want to understand how to navigate. That means walking though articles, then switching to another feed.
* I want to understand how to delete all the articles for the current feed using a shortcut. I cannot seem to find one.
* I want to understand how to mark read all the articles for the current feed. Again, I don't see it in options.
* I want to be able to delete articles one by one immediately without marking them "Deleted". Looks like they disappear only after switching to another feed and back.
* I want to have a shortcut to delete all the articles for the feed. Something simple, like Ctrl + Delete. Currently the app offers to delete the feed itself. Why are you saying _"You are about to completely delete **item** "DistroWatch.com: Packages". Are you sure?"_ It's not an "item", it's a **feed**.
* There's no option to undo any changes. Ctrl + Z should be able to undelete deleted articles, or mark them unread.
* New articles should appear on top by default. For some reasons RSSGuard defaults to new articles at the bottom. Imagine you have several screens worth of articles. That means you'll have to scroll a lot.
* Lastly, right mouse click a single article and you'll see "Delete articles" (yeah, in plural). Why? It's extremely confusing. I expect it to show "Delete an article" for a single selected article or "Delete articles" for multiple selected articles. Actually, why not just put "Delete"? The same applies to "Mark articles read/unread". Plural all the time. Why not just "Mark read/unread"?

You have to fix terminology, please.
* When you are talking about items, please write "article(s)". Forget about "Item", item applies to anything and everything.
* When you are talking about feeds, please write "feed(s)"
* There's no need to duplicate the entity itself in its popup menu. It's obvious you're working with articles or feeds when your right mouse clicking them.

E.g. for a feed pop-up:

![feed-pop-up](https://user-images.githubusercontent.com/4958603/236212130-6126a698-9f56-489c-92a3-f6a7580eb2f0.png)

No, no, no.

What it should have been:
* Fetch **or Update** ("Selected" is _redundant_ and _wrong_ here, you cannot select multiple feeds)
* Copy URL
* View in newspaper mode (OK)
* Mark read
* Mark unread
* Add new category (OK)
* Add new feed (OK)
* Move up/down/to top/bottom (OK)
* Fetch metatada (OK)
* "Properties" or just "Edit" instead of "Edit selected item" at the top.

Why the delete icon for the feed is different for the delete icon for the article? Why not ❌ for both?

Sorry, there's a wall of text but I'm not ready to put everything into bug reports or features because you may have a different opinion on everything, so I don't want to waste your time.

**Comment by martinrotter** [comment]
Hi.

First to say - pull requests are welcomed. Your are welcomed to use your free time and contribute the actual well-structured code into the project like I do for past 10 years.

Now, you combined several feature requests into single ticket and that is big no-no for me. Create separate tickets for each single request you have.

More:
* when there is "item" in GUI, it really IS item because feed list contains not just feeds but many other ITEM types
* when there is some operation with articles, it says in GUI that it is operation with articles
* "delete" icons for feed/articles are different, because you delete different things, majority of icon themes offers specific icon for deleting messages, so I used that
* as for navigating through program via keyboard shortcuts - there are actions (menu items) and all of them can be assigned to custom keyboard shortcut in settings - there are actions for navigating to next (first) article, previous article, next UNREAD articles (which works across all feeds), next feed, previous feed etc.
* yes, by default the sorting of articles is not suitable for everyone, you literally have to click once to change default sorting column and order and that setting is persistent - what's the deal?
* undo-redo system will not happen as this was not really ever requested and would be too much of a coding for me right now for no real benefit - when you delete feed you get confirmation dialog, when you delete articles, they are moved in recycle bin so you really cannot "lose" data that easily
* there is literally action "Mark selected item read/unread" which marks all articles of selected item as (you guessed it) read or unread

Maybe when you launched RSS Guard, you forgot that RSS Guard is neither Akregator nor QuiteRSS.

Feel free to respond here, I close the ticket as it does not meet basic rule (each separate BUG or FR -> ticket).
